-- Sin Tachar — publicar artículo de Injusticia social (pega TODO en Supabase → SQL Editor → Run).
-- Queda PUBLICADO en /es y /en, autorado por tu admin. Cambia el email si usaste otro.
-- ⚠️ Córrelo DESPUÉS de que Vercel redespliegue (para que exista la portada SVG).
do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then
    raise exception 'No encontré ese usuario. Regístrate primero o cambia el email en este script.';
  end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'injusticia', 'cuando-el-sistema-dice-no',
     'Cuando el sistema dice "no": el costo humano de decidir por algoritmo', 'When the System Says "No": The Human Cost of Deciding by Algorithm',
     'Gobiernos que prometieron eficiencia están dejando sin ayuda a quienes menos margen tienen. El algoritmo no sufre el error; lo sufre una madre gitana, un anciano con discapacidad, una familia migrante. Y México acaba de poner un requisito biométrico en el camino de su pensión.', 'Governments that promised efficiency are cutting off aid to the people with the least room to absorb the loss. The algorithm doesn''t suffer the error; a Roma mother, a disabled elder, a migrant family does. And Mexico has just placed a biometric requirement on the path to its pension.',
     'Antes de que un funcionario la mirara a los ojos, un sistema informático ya había decidido que no merecía ayuda. En Serbia, la Tarjeta Social cruza alrededor de 130 tipos de datos para calcular quién tiene derecho a la asistencia del Estado. Desde 2022, más de 60,000 personas quedaron fuera de esa ayuda —23,000 solo en los primeros diez meses—, según el Grupo de Trabajo de la ONU sobre Empresas y Derechos Humanos. No es un accidente estadístico repartido al azar: el golpe cae de forma desproporcionada sobre la comunidad romaní (gitana) y sobre personas con discapacidad, cuyos ingresos informales el sistema malinterpreta como riqueza oculta. Amnistía Internacional lo describe sin eufemismos: el sistema refuerza una discriminación estructural que ya existía.

Conviene decir con claridad qué está en juego y qué no. No hablamos de robots que se rebelan ni de un debate abstracto sobre inteligencia artificial. Hablamos de decisiones cotidianas —conceder o negar una medicina, una pensión, un plato de comida— que los Estados han empezado a delegar en sistemas automáticos, y del daño concreto que eso produce cuando el sistema se equivoca. Porque el algoritmo no pasa hambre. Quien pasa hambre es la persona a la que el sistema, en silencio, marcó como indebida.

El patrón se repite en países muy distintos. En junio de 2026, Amnistía Internacional publicó "Automating Suspicion", un informe que documenta cómo los sistemas de perfilado de riesgo generan acusaciones falsas contra grupos ya marginados —personas racializadas, con discapacidad o enfermedad crónica, de bajos ingresos y migrantes— en Australia, Dinamarca, Francia y Países Bajos. El caso australiano, conocido como Robodebt, llegó a acusar de fraude a unas 400,000 personas por deudas que el propio algoritmo inventaba. Amnistía no pide ajustar la máquina: pide prohibir estos sistemas en contextos de alto riesgo, porque los considera incompatibles con el derecho internacional.

Tampoco es un problema lejano de Europa o de las antípodas. En Estados Unidos, el estado de Tennessee pagó a la consultora Deloitte más de 400 millones de dólares por TennCare Connect, el sistema que decide quién accede a Medicaid, el seguro médico para personas de bajos ingresos. Un juez federal falló que el sistema cargaba mal los datos, asignaba a las personas al hogar equivocado y negó ilegalmente cobertura de salud a miles, incluidas personas con discapacidad. Detrás de esa palabra —"miles"— hay gente que se quedó sin tratamiento mientras un software procesaba mal su expediente.

Aquí es donde América Latina debe mirarse con honestidad, sin caer en la alarma fácil. Desde febrero de 2026, la CURP biométrica es obligatoria en México para trámites y programas sociales, y el gobierno la exigirá para registrarse en la Pensión del Bienestar. Es importante ser justos: hasta la fecha no existe un caso documentado de una pensión negada o suspendida en México por un fallo del sistema. No lo afirmamos, porque no ha ocurrido o no se ha probado. Pero sí señalamos un punto de fricción conocido. Un requisito biométrico obligatorio para cobrar una pensión es exactamente el tipo de barrera que en Serbia dejó fuera a los más vulnerables: el adulto mayor rural sin documentos en regla, la persona cuya huella dactilar el lector no reconoce, quien no puede desplazarse a registrarse. Lo levantamos como advertencia, no como acusación. La lección de los otros países es que el momento de vigilar un sistema así es antes de que produzca su primera víctima, no después.

La historia reciente ya dejó un aviso. En Países Bajos, el escándalo del toeslagenaffaire acusó falsamente de fraude a unas 35,000 familias, muchas de origen migrante, y en 2021 tumbó al gobierno. Cuando Ámsterdam intentó construir después un sistema de bienestar "justo", en junio de 2025 tuvo que admitir que había fracasado.

La eficiencia no es un valor neutral cuando su precio lo paga siempre la misma gente. Detrás de cada expediente rechazado hay una persona que ese día no comió, no se trató o no cobró lo que le correspondía. Nombrar eso —exigir que un ser humano pueda revisar la decisión de una máquina, que exista un recurso real, que nadie pierda su pensión por un lector de huellas— no es estar en contra de la tecnología. Es estar a favor de las personas. ¿Qué salvaguardas deberíamos exigir antes de que un sistema automático decida quién merece ayuda en tu país? Esa conversación empieza ahora.', 'Before a caseworker ever looked her in the eye, a computer had already decided she didn''t deserve help. In Serbia, the Social Card system cross-references some 130 types of data to calculate who qualifies for state assistance. Since 2022, more than 60,000 people have been cut off from that aid—23,000 in the first ten months alone—according to the UN Working Group on Business and Human Rights. This is not a statistical accident spread evenly across the population: the blow falls disproportionately on the Roma community and on people with disabilities, whose informal earnings the system misreads as hidden wealth. Amnesty International describes it without euphemism: the system reinforces a structural discrimination that was already there.

It is worth being clear about what is at stake and what is not. We are not talking about robots that rebel, nor about an abstract debate over artificial intelligence. We are talking about everyday decisions—granting or denying a medicine, a pension, a plate of food—that states have begun to hand over to automated systems, and about the concrete harm that follows when the system gets it wrong. Because the algorithm does not go hungry. The one who goes hungry is the person the system quietly flagged as undeserving.

The pattern repeats across very different countries. In June 2026, Amnesty International published "Automating Suspicion," a report documenting how risk-profiling systems generate false accusations against already marginalized groups—racialized people, those with disabilities or chronic illness, low-income people, and migrants—in Australia, Denmark, France, and the Netherlands. Australia''s case, known as Robodebt, ended up accusing roughly 400,000 people of fraud over debts the algorithm itself invented. Amnesty is not asking for the machine to be fine-tuned: it is calling for these systems to be banned in high-risk contexts, because it deems them incompatible with international law.

Nor is this a distant problem confined to Europe or the far side of the world. In the United States, the state of Tennessee paid the consultancy Deloitte more than 400 million dollars for TennCare Connect, the system that decides who gets Medicaid, the health coverage for low-income people. A federal judge ruled that the system loaded data incorrectly, assigned people to the wrong household, and illegally denied health coverage to thousands, including people with disabilities. Behind that word—"thousands"—are people left without treatment while a piece of software mishandled their file.

This is where Latin America must look at itself honestly, without slipping into easy alarm. Since February 2026, the biometric CURP has been mandatory in Mexico for official procedures and social programs, and the government will require it to register for the Pensión del Bienestar, the old-age welfare pension. It is important to be fair: to date there is no documented case of a pension in Mexico being denied or suspended because of a system failure. We do not claim there is, because it has not happened—or has not been proven. But we do flag a known point of friction. A mandatory biometric requirement to collect a pension is exactly the kind of barrier that, in Serbia, shut out the most vulnerable: the rural elder without papers in order, the person whose fingerprint the reader cannot read, the one who cannot travel to register. We raise it as a warning, not an accusation. The lesson from other countries is that the time to watch a system like this is before it produces its first victim, not after.

Recent history has already left a warning. In the Netherlands, the toeslagenaffaire scandal falsely accused some 35,000 families, many of migrant background, of fraud, and in 2021 it brought down the government. When Amsterdam later tried to build a "fair" welfare system, by June 2025 it had to admit the attempt had failed.

Efficiency is not a neutral value when the same people always pay its price. Behind every rejected file is a person who that day did not eat, did not get treated, or did not receive what was owed to them. Naming that—demanding that a human being be able to review a machine''s decision, that a real avenue of appeal exist, that no one lose their pension to a fingerprint reader—is not being against technology. It is being for people. What safeguards should we demand before an automated system decides who deserves help in your country? That conversation starts now.',
     '/covers/injusticia-algoritmica.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;
