-- Sin Tachar — sección VIDEOJUEGOS + 2 artículos de Sony (pega TODO en SQL Editor → Run).
-- ⚠️ Córrelo DESPUÉS del redeploy de Vercel (por las portadas SVG).

-- Categoría Videojuegos (idempotente)
insert into public.categories (slug,name_es,name_en,sort_order)
  values ('videojuegos','Videojuegos','Video games',5) on conflict (slug) do nothing;
update public.categories set sort_order=6 where slug='ia-segura';

do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then raise exception 'No encontré ese usuario. Regístrate o cambia el email.'; end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'videojuegos', 'sony-fin-formato-fisico-playstation-quien-paga',
     'El disco que Sony deja morir: qué perdemos cuando el juego se vuelve licencia', 'The Disc Sony Is Letting Die: What We Lose When a Game Becomes a License',
     'Sony dejará de fabricar discos para juegos nuevos de PlayStation en enero de 2028. La letra chica ya la conocemos: comprar no es poseer. Y el costo lo paga quien depende del usado.', 'Sony will stop making discs for new PlayStation games in January 2028. We already know the fine print: buying isn''t owning. And the cost falls on whoever depends on the second-hand market.',
     'El 1 de julio de 2026 Sony lo hizo oficial en su propio blog: cesará la producción de discos físicos para todos los juegos nuevos que salgan en consolas PlayStation a partir de enero de 2028. Después de esa fecha, los títulos nuevos existirán únicamente en formato digital, en PlayStation Store o como códigos en tienda. Los juegos ya lanzados en disco, o que salgan antes de enero de 2028, no se ven afectados: seguirán funcionando, revendiéndose y existiendo. Sid Shuman, directivo de SIE, lo enmarcó como un movimiento de la industria que "se aleja de los discos físicos hacia lo digital". El comunicado no trae porcentajes ni cifras.

Aquí conviene ser honesto con los números, porque circulan dos que miden cosas distintas. Por un lado, medios reportan un ~85% digital contra 15% físico, pero eso es participación de ventas de software de juego completo en PS4/PS5, no un dato del blog oficial. Por otro, Slate cita que en 2024 los discos fueron apenas el 3% de todas las ventas de la marca PlayStation (que incluye hardware y servicios) y que la compañía movió alrededor de 70 millones de discos en 2025. Son cosas diferentes: no las mezclen. Sony, oficialmente, solo habla de "preferencia del consumidor".

El corazón del problema no es la nostalgia por el plástico. Es esto: comprar no es poseer. Los términos de PlayStation Network dicen, con todas sus letras, que "purchase" o "buy" no transfieren propiedad; todo se licencia de forma revocable. Y no es teoría. En junio de 2026 Sony avisó a usuarios de Reino Unido y Europa que el 1 de septiembre eliminaría 551 películas y series de StudioCanal ya "compradas", sin reembolso, porque venció el acuerdo de licencia. Ya había pasado antes con contenido de Discovery en 2023, revertido solo tras las protestas. Cuando el disco desaparece, esa cláusula deja de ser letra chica y se vuelve la única realidad.

De ahí sale el otro costo silencioso: la preservación. Las licencias caducan y los juegos se evaporan. Metal Gear Solid salió de tiendas digitales por líos con material de archivo; en un mundo sin disco, un juego así simplemente deja de existir. Cuando se planteó cerrar las tiendas de PS3 y Vita, se calculó que unos 2,200 juegos digitales dejarían de venderse, y 138 de ellos no existen en ninguna otra plataforma. La campaña Stop Killing Games recoge firmas, pero hasta ahora no ha conseguido ninguna reforma legal en Reino Unido, la UE ni Estados Unidos. El único contrapeso concreto es tímido: la ley californiana AB 2426, vigente desde enero de 2025, obliga a avisar cuando una "compra" digital es en realidad una licencia. Avisa; no impide que te la quiten.

¿Y quién paga la cuenta? El coleccionista pierde el objeto. El jugador de reventa pierde la forma de recuperar valor o de comprar barato de segunda mano. Y aquí va lo que el dossier no confirma con fuente específica para la región, así que lo digo como lectura y no como dato duro: en México y LatAm, donde el mercado usado abarata el acceso y donde el internet no siempre alcanza para descargar juegos cada vez más pesados, "sin disco" puede terminar significando "sin entrada". Un modelo 100% digital traslada ese costo al consumidor con menos margen, no al que ya paga suscripciones cómodo.

No es un adiós al plástico por capricho tecnológico. Es un cambio en la relación entre quien juega y quien vende: de dueño a arrendatario. La pregunta que dejamos abierta es tuya: ¿comprarías una biblioteca que la tienda puede apagar? ¿Te cambia la ecuación si vives donde el usado es la puerta de entrada? Cuéntanos en los comentarios cómo lo ves desde donde estás.', 'On July 1, 2026, Sony made it official on its own blog: it will stop producing physical discs for all new games launching on PlayStation consoles starting January 2028. After that date, new titles will exist in digital form only, on the PlayStation Store or as in-store codes. Games already released on disc, or launching before January 2028, are not affected: they will keep working, keep being resold, keep existing. Sid Shuman, an SIE director, framed it as an industry moving "away from physical discs and toward digital." The announcement carries no percentages and no figures.

It is worth being honest about the numbers, because two are circulating and they measure different things. On one hand, outlets report roughly 85% digital versus 15% physical, but that is the share of full-game software sales on PS4/PS5, not a figure from the official blog. On the other, Slate cites that in 2024 discs were just 3% of all PlayStation-brand sales (which includes hardware and services), and that the company moved around 70 million discs in 2025. These are not the same metric, so don''t blend them. Officially, Sony only talks about "consumer preference."

The heart of the issue is not nostalgia for plastic. It''s this: buying is not owning. PlayStation Network''s terms say, in plain words, that "purchase" or "buy" do not transfer ownership; everything is licensed on a revocable basis. And this is not theory. In June 2026, Sony told users in the UK and Europe that on September 1 it would remove 551 StudioCanal films and series they had already "purchased," with no refund, because the licensing deal expired. It had happened before with Discovery content in 2023, reversed only after backlash. When the disc disappears, that clause stops being fine print and becomes the only reality.

From there comes the other quiet cost: preservation. Licenses expire and games evaporate. Metal Gear Solid was pulled from digital stores over issues with archival footage; in a discless world, a game like that simply ceases to exist. When closing the PS3 and Vita stores was floated, it was estimated that some 2,200 digital games would stop being sold, and 138 of them exist on no other platform. The Stop Killing Games campaign is gathering signatures, but so far it has secured no legal reform in the UK, the EU, or the United States. The one concrete counterweight is timid: California''s AB 2426 law, in force since January 2025, requires sellers to disclose when a digital "purchase" is really a license. It warns you; it does not stop them from taking it away.

So who pays the bill? The collector loses the object. The resale player loses the way to recover value or buy cheap second-hand. And here is what the dossier does not confirm with a region-specific source, so I offer it as a reading rather than hard data: in Mexico and Latin America, where the used market makes access cheaper and where internet isn''t always enough to download increasingly large games, "no disc" can end up meaning "no entry." A 100% digital model shifts that cost onto the consumer with the least margin, not onto the one already paying subscriptions comfortably.

This is not a goodbye to plastic on a technological whim. It''s a shift in the relationship between the player and the seller: from owner to renter. The question we leave open is yours: would you buy a library the store can switch off? Does the math change if you live where used copies are the way in? Tell us in the comments how it looks from where you are.',
     '/covers/sony-formato-fisico.svg', 'published', now()),
    (admin_id, 'videojuegos', 'sony-pesos-mexico-dolar-20-50-playstation',
     'Sony cobrará en pesos en México: el "dólar a 20.50" que ya molesta a los jugadores', 'Sony will charge in pesos in Mexico: the "20.50 dollar" already upsetting players',
     'La PlayStation Store dejará de cobrar en dólares en México a partir del 20 de agosto de 2026. La letra chica: Sony fijará su propio tipo de cambio en 20.50 pesos por dólar, muy por encima del dólar real de ~17.4.', 'The PlayStation Store will stop charging in dollars in Mexico starting August 20, 2026. The fine print: Sony sets its own exchange rate at 20.50 pesos per dollar, well above the real ~17.4 dollar.',
     'Después de años vendiendo en dólares, la PlayStation Store empezará a mostrar y cobrar precios en pesos mexicanos. El anuncio se hizo público el 17 de julio de 2026 y el cambio se ejecutará durante una ventana de mantenimiento de la tienda entre el 18 y el 20 de agosto de 2026. La medida aplica también a Honduras y Nicaragua. Suena a buena noticia —adiós a la conversión mental y a las comisiones del banco— pero el costo real para quien paga está escondido en un número: Sony fijará su propio tipo de cambio interno en 20.50 pesos por dólar.

Ahí está el problema. Según los reportes de prensa, el tipo de cambio de mercado en esos mismos días de julio de 2026 rondaba los 17.38 a 17.52 pesos por dólar (el FIX de Banxico fue de 17.50 el 13 de julio, y el peso cerró en 17.38 el 15 de julio). Sony está aplicando un tipo de cambio más de 3 pesos por encima del real, un sobreprecio implícito cercano al 17 o 18 por ciento sobre la paridad de mercado, incluso antes de discutir impuestos.

El ejemplo que circuló en la prensa usa GTA 6 (79.99 dólares). Con el esquema actual, 79.99 dólares más unos 12.80 de impuesto dan alrededor de 92.79 dólares, es decir unos 1,626 pesos al cambio de mercado. Con el nuevo precio en pesos a 20.50, el cálculo periodístico da aproximadamente 1,640 pesos. La diferencia en ese ejemplo puntual es pequeña, y por eso medios como Xataka especulan que el 20.50 ya podría incluir el IVA del 16 por ciento. Hay que ser claros: eso NO está confirmado. Sony no aclaró si los impuestos seguirán cobrándose por separado, y ese es justo el dato que hoy no se puede afirmar. El ejemplo de GTA 6 es un cálculo de prensa, no una lista de precios oficial de Sony.

Conviene también matizar el propio "dólar a 20" del que todos hablan: lo confirmado es que Sony usará 20.50, no un redondo 20. Y el dólar real en julio de 2026 está en torno a 17.4, no en 20. Es decir, el número que Sony eligió para su tienda vive en un universo distinto al del mercado cambiario.

Vale la pena recordar por qué ocurre esto ahora, porque no fue voluntad de Sony. La Profeco actuó tras una queja de usuarios y notificó a la empresa que la ley mexicana obliga a exhibir precios en moneda nacional, advirtiendo posibles sanciones. El origen viene de una denuncia de agosto de 2025, cuando jugadores señalaron que el precio final con IVA solo aparecía en el último paso de la compra. El comunicado oficial de Sony lo vende como una simplificación, y en sus palabras están "simplificando las compras en PlayStation Store en México al mostrar los precios en Pesos Mexicanos". La comunidad no lo leyó igual: pasar a pesos era exactamente lo que se pedía, pero ante la falta de una explicación clara sobre el 20.50 y sobre el IVA, muchos jugadores mexicanos expresaron molestia en redes, temiendo terminar pagando más caro que con la conversión directa actual.

Este episodio no llega en el vacío. En abril de 2025 Sony ya había subido PS Plus en México y toda LatAm en todos sus niveles, con el plan anual Essential pasando de 54.99 a 64.99 dólares. La tienda de PlayStation, a diferencia de Xbox o Steam, ha operado históricamente en dólares en México, dejando el precio de cada juego a merced del tipo de cambio. Y el contexto de poder adquisitivo duele: el salario mínimo general subió a 315.04 pesos diarios desde enero de 2026. Un solo juego AAA de alrededor de 1,600 pesos supera cinco días de ese salario mínimo íntegro.

La pregunta abierta, y la que más importa a quien paga, es simple: ¿el 20.50 incluye o no el IVA? De esa respuesta depende que la migración a pesos sea un alivio o un aumento disfrazado. Hoy Sony no lo ha aclarado. ¿Tú qué crees que va a pasar cuando la tienda cambie el 20 de agosto? Cuéntanos en los comentarios cómo te está pegando el precio del gaming en México.', 'After years of selling in dollars, the PlayStation Store will start displaying and charging prices in Mexican pesos. The announcement became public on July 17, 2026, and the switch will happen during a store maintenance window between August 18 and August 20, 2026. The measure also applies to Honduras and Nicaragua. It sounds like good news, goodbye to mental math and bank conversion fees, but the real cost for whoever pays is hidden in one number: Sony will set its own internal exchange rate at 20.50 pesos per dollar.

That is the problem. According to press reports, the market exchange rate during those same days of July 2026 hovered between 17.38 and 17.52 pesos per dollar (Banxico''s FIX rate was 17.50 on July 13, and the peso closed at 17.38 on July 15). Sony is applying an exchange rate more than 3 pesos above the real one, an implicit markup close to 17 or 18 percent over the market rate, even before we get into taxes.

The example that circulated in the press uses GTA 6 (79.99 dollars). Under the current scheme, 79.99 dollars plus roughly 12.80 in tax comes to about 92.79 dollars, or around 1,626 pesos at the market rate. With the new peso price at 20.50, the journalistic calculation lands at approximately 1,640 pesos. The difference in that specific example is small, which is why outlets like Xataka speculate that the 20.50 might already include the 16 percent VAT. Let us be clear: that is NOT confirmed. Sony did not clarify whether taxes will still be charged separately, and that is exactly the data point no one can assert today. The GTA 6 example is a press calculation, not an official Sony price list.

It is also worth qualifying the "20 dollar" figure everyone is talking about: what is confirmed is that Sony will use 20.50, not a round 20. And the real dollar in July 2026 is around 17.4, not 20. In other words, the number Sony chose for its store lives in a different universe than the currency market.

It is worth remembering why this is happening now, because it was not Sony''s initiative. Profeco, Mexico''s consumer protection agency, acted after user complaints and notified the company that Mexican law requires displaying prices in national currency, warning of possible penalties. The origin traces back to a complaint in August 2025, when players pointed out that the final price with VAT only appeared at the last step of the purchase. Sony''s official statement frames it as a simplification, saying in its own words that it is "simplifying purchases on the PlayStation Store in Mexico by showing prices in Mexican Pesos." The community did not read it the same way: switching to pesos was exactly what was requested, but with no clear explanation about the 20.50 or the VAT, many Mexican players voiced frustration on social media, fearing they will end up paying more than under the current direct conversion.

This episode does not arrive in a vacuum. In April 2025 Sony had already raised PS Plus in Mexico and across Latin America at every tier, with the annual Essential plan going from 54.99 to 64.99 dollars. Unlike Xbox or Steam, the PlayStation store has historically operated in dollars in Mexico, leaving every game''s price at the mercy of the exchange rate. And the purchasing-power context stings: Mexico''s general minimum wage rose to 315.04 pesos per day as of January 2026. A single AAA game at around 1,600 pesos exceeds five full days of that minimum wage.

The open question, and the one that matters most to whoever pays, is simple: does the 20.50 include VAT or not? Whether the move to pesos is a relief or a disguised increase depends on that answer. Sony has not clarified it yet. What do you think will happen when the store changes on August 20? Tell us in the comments how gaming prices are hitting you in Mexico.',
     '/covers/sony-precios-mexico.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;
