-- Sin Tachar — publicar artículos de MÚSICA y ARTE (pega TODO en Supabase → SQL Editor → Run).
-- Publicados en /es y /en, autorados por tu admin. ⚠️ Córrelo DESPUÉS del redeploy de Vercel (por las portadas SVG).
do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then
    raise exception 'No encontré ese usuario. Regístrate primero o cambia el email.';
  end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'musica', 'corridos-censura-mexico-cuando-callar-la-cancion',
     'Cuando callar la canción no calla la violencia: los corridos entre la censura y la crónica', 'When Silencing the Song Doesn''t Silence the Violence: Mexico''s Corridos Between Censorship and Chronicle',
     'En abril de 2025 un público destrozó los instrumentos sobre el escenario porque un cantante obedeció a la autoridad y se negó a tocar narcocorridos. Detrás de esa escena hay un año en que diez estados mexicanos prohibieron uno de los géneros más escuchados del país, Estados Unidos revocó visas y el gobierno respondió con un concurso para "orientar" las letras. La pregunta sigue abierta: ¿se puede callar una canción sin callar aquello que la produjo?', 'In April 2025 an audience smashed the instruments on stage because a singer obeyed the authorities and refused to play narcocorridos. Behind that scene lies a year in which ten Mexican states banned one of the country''s most-streamed genres, the United States revoked visas, and the government answered with a contest to "reorient" the lyrics. The question stays open: can you silence a song without silencing what produced it?',
     'El 11 de abril de 2025, en el palenque de la Feria de Texcoco, Luis R. Conríquez subió al ruedo y anunció lo que muchos no querían escuchar: por disposición oficial, esa noche no habría narcocorridos. Lo que siguió no fue un silencio respetuoso, sino una revuelta. El público lo abucheó, lanzó objetos y terminó destrozando los instrumentos sobre el escenario; el show acabó en desalojo, y una presentación posterior en Metepec fue cancelada. En esa escena —un cantante que acata a la autoridad y un público que se siente traicionado— está el nudo del año más tenso para uno de los géneros más escuchados de México.

Los corridos tumbados, esa fusión del regional mexicano con el trap y el hip-hop que llevó a artistas como Natanael Cano y Junior H a lo más alto del streaming global, arrastran una vieja contradicción: son, a la vez, crónica de un país en guerra narrada desde abajo y, en su vertiente más cruda, vitrina que romantiza a los capos. En 2025 esa tensión estalló en política pública.

Durante ese año, diez estados —entre ellos Michoacán, Jalisco, Nayarit, Chihuahua, Aguascalientes, Baja California, Guanajuato, Quintana Roo, Querétaro y el Estado de México— restringieron los narcocorridos en eventos públicos, con multas millonarias y procesos por "apología del delito". Chihuahua había sido pionero desde 2023, con sanciones que iban de 735 mil a 1.35 millones de pesos. Sinaloa y Sonora suspendieron conciertos alegando seguridad. El costo para los artistas fue inmediato: giras interrumpidas, autocensura sobre el escenario y el miedo a que una canción se volviera delito.

El caso más sonado cruzó la frontera. A fines de marzo de 2025, Los Alegres del Barranco proyectaron la imagen de "El Mencho", líder del CJNG, durante un concierto en un recinto de la Universidad de Guadalajara. Estados Unidos les revocó la visa, Jalisco abrió una carpeta de investigación y, más tarde, un juez les concedió un amparo en nombre de la libertad de expresión artística. Natanael Cano y Junior H también enfrentaron sanciones e indagatorias. La censura, lejos de apagar el género, lo empujó al centro del debate nacional.

La respuesta del gobierno federal no fue prohibir, sino orientar. En abril de 2025 la presidenta Claudia Sheinbaum lanzó "México Canta", un concurso binacional que reunió a unos 15 mil jóvenes de ambos lados de la frontera para componer canciones "sin apología de la violencia". En la final, con 222,955 votos, ganaron Sergio Maya, de Hidalgo, con "Quiero soñar", y Carmen María junto a Galia Siurob, de Tijuana. En mayo de 2026 Sheinbaum presentó la segunda edición desde Palacio Nacional, acompañada nada menos que por Junior H y Majo Aguilar: el mismo Estado que multa el género buscaba ahora reencauzarlo.

Aquí está lo que incomoda. Los corridos no inventaron la violencia que narran; la registran, a veces con complacencia, a veces como el único archivo que ciertas comunidades tienen de su propia herida. Prohibir la canción no desaparece los desplazamientos, las desapariciones ni el poder real de los cárteles que la canción, en su peor cara, celebra. Pero dejarla intacta tampoco es neutral cuando esas letras convierten a un capo en héroe. Entre la libertad de expresión y la responsabilidad sobre lo que se glorifica, México lleva dos años sin encontrar la nota justa, y en 2026 la discusión sigue abierta.

Nos interesa lo que ustedes escuchan en todo esto. ¿Es un corrido una crónica que incomoda al poder o una publicidad que le hace el trabajo al crimen? ¿Puede el Estado "reeducar" un género sin volverse censor? Cuéntennos desde dónde lo oyen: la conversación, como la música, apenas empieza.', 'On April 11, 2025, at the palenque of the Texcoco Fair, Luis R. Conríquez stepped into the ring and announced what many did not want to hear: by official order, there would be no narcocorridos that night. What followed was not a respectful silence but a riot. The crowd booed him, threw objects, and ended up smashing the instruments on stage; the show ended in evacuation, and a later performance in Metepec was canceled. In that scene —a singer obeying the authorities and an audience that feels betrayed— lies the knot of the tensest year for one of Mexico''s most-streamed genres.

Corridos tumbados, that fusion of regional Mexican music with trap and hip-hop that pushed artists like Natanael Cano and Junior H to the top of global streaming, carry an old contradiction: they are at once a chronicle of a country at war told from below and, in their rawest form, a showcase that romanticizes the kingpins. In 2025 that tension exploded into public policy.

Over that year, ten states —among them Michoacán, Jalisco, Nayarit, Chihuahua, Aguascalientes, Baja California, Guanajuato, Quintana Roo, Querétaro, and the State of Mexico— restricted narcocorridos at public events, with steep fines and prosecutions for "apología del delito," the glorification of crime. Chihuahua had been the pioneer since 2023, with penalties ranging from 735,000 to 1.35 million pesos. Sinaloa and Sonora suspended concerts citing security. The cost to artists was immediate: interrupted tours, self-censorship on stage, and the fear that a song might become a crime.

The most notorious case crossed the border. In late March 2025, Los Alegres del Barranco projected the image of "El Mencho," leader of the CJNG cartel, during a concert at a University of Guadalajara venue. The United States revoked their visas, Jalisco opened an investigation, and later a judge granted them an injunction in the name of artistic freedom of expression. Natanael Cano and Junior H also faced sanctions and inquiries. Censorship, far from muffling the genre, pushed it to the center of the national debate.

The federal government''s response was not to ban but to redirect. In April 2025, President Claudia Sheinbaum launched "México Canta," a binational contest that gathered some 15,000 young people from both sides of the border to compose songs "without glorifying violence." In the final, with 222,955 votes, the winners were Sergio Maya, from Hidalgo, with "Quiero soñar," and Carmen María alongside Galia Siurob, from Tijuana. In May 2026, Sheinbaum presented the second edition from the National Palace, accompanied by none other than Junior H and Majo Aguilar: the same state that fines the genre was now trying to steer it.

Here is what unsettles. Corridos did not invent the violence they narrate; they record it, sometimes with complacency, sometimes as the only archive certain communities have of their own wound. Banning the song does not erase the displacements, the disappearances, or the real power of the cartels that the song, at its worst, celebrates. But leaving it untouched is not neutral either, when those lyrics turn a kingpin into a hero. Between freedom of expression and responsibility for what gets glorified, Mexico has spent two years unable to find the right note, and in 2026 the discussion remains open.

We care about what you hear in all this. Is a corrido a chronicle that discomforts power, or advertising that does crime''s work for it? Can the state "reeducate" a genre without becoming a censor? Tell us where you are listening from: the conversation, like the music, is only just beginning.',
     '/covers/musica-corridos.svg', 'published', now()),
    (admin_id, 'arte', 'arte-memoria-buscadoras-mexico-2026',
     'Bordar un nombre para que no lo borre la cifra', 'Stitching a Name So the Statistics Can''t Erase It',
     'De un muro en Ciudad Juárez a un bordado en Torreón, las familias buscadoras de México convirtieron el arte en el último lugar donde sus desaparecidos siguen teniendo cara, oficio y color favorito. No es decoración: es resistencia contra el olvido de Estado.', 'From a wall in Ciudad Juarez to embroidery in Torreon, Mexico''s searching families have made art the last place where their disappeared still have a face, a trade, a favorite color. It isn''t decoration: it''s resistance against a state that would rather they be forgotten.',
     'El 18 de febrero de 2026, en Ciudad Juárez, cinco rostros nuevos aparecieron en un muro. No eran fichas de búsqueda ni cifras de expediente. Eran Alfonso Guadián, Mauricio Maese, Jorge Ernesto Alanís, Juan Antonio Campos y Raymundo Iván Álvarez, pintados no por cómo desaparecieron sino por cómo vivían: su oficio, su comida, sus colores favoritos. El colectivo Familias Unidas por la Verdad y la Justicia develó los murales tras un proceso de arteterapia coordinado por la artista Ana Infante, que lo resumió sin adornos: "Este memorial es resistencia. Son personas amadas y esperadas." El Memorial Memoria Viva funciona desde 2021 como algo más que una pared: es punto de encuentro, de organización, de sostén entre quienes buscan.

Hay una idea incómoda en el centro de este arte, y conviene decirla de frente. Cuando el Estado convierte a una persona en un número de una estadística que además prefiere no actualizar, nombrarla se vuelve un acto político. Pintar su cara es negarse a la aritmética del olvido. Por eso lo que ocurre en México este ciclo no cuelga en museos con aire acondicionado: se pinta en muros y se borda en plazas, con las manos de quienes cargan la ausencia.

El hilo, literalmente, aparece en Torreón. El 7 de mayo de 2026, el colectivo Voz que clama justicia por personas desaparecidas bordó en la Plaza Mayor los nombres y expedientes de sus desaparecidos, con una exigencia clara a las autoridades: no maquillar las cifras. El gesto es preciso y demoledor. El bordado toma el dato frío del expediente —ese lenguaje burocrático que despersonaliza— y lo devuelve al cuerpo, a la aguja, al tiempo lento de quien cose un nombre puntada por puntada en el espacio público. Donde el informe oficial resume, el hilo insiste. Donde la cifra redondea, la tela nombra.

En la Ciudad de México, en el marco del Día de las Madres Buscadoras, el Colectivo Hilos intervino un monumento con una pieza colectiva de tela roja, integrada a la marcha nacional de madres buscadoras que avanzaba rumbo a la Fiscalía General de la República. El rojo como metáfora de los feminicidios y las desapariciones convierte la piedra oficial —esos monumentos que el Estado erige a su propia versión de la historia— en un lienzo de duelo y denuncia. La ciudad se vuelve, por un día, un archivo de heridas abiertas que nadie autorizó a cerrar.

Tres ciudades, tres materiales, una misma pregunta escalando: del muro al textil, del barrio a la plaza. Y el arco no se cierra en México. En la 61ª Bienal de Venecia de 2026, titulada "In Minor Keys", el pabellón argentino presenta "Oscuridad visible: la larga sombra de la dictadura", organizado por el Museo de Arte Moderno de Buenos Aires, sobre el terrorismo de Estado. La memoria del Cono Sur y las desapariciones del México actual dialogan sin necesidad de traducción: en ambos casos, el arte hace el trabajo que las instituciones no quisieron hacer, sostener la memoria cuando el poder prefiere el silencio.

Vale la pena detenerse en lo que estas obras no son. No son monumentos triunfales ni catarsis estética para el visitante. Son objetos de uso: puntos de organización, espacios de terapia, herramientas de exigencia. El arte aquí no ilustra la lucha; es la lucha en su forma más tenaz, la de nombrar cuando nombrar cuesta y duele. Ana Infante lo dijo con una economía que ningún crítico mejoraría: personas amadas y esperadas.

Queda la pregunta que atraviesa todo esto y que preferimos dejar abierta, no resuelta. Cuando el Estado abandona la memoria, alguien tiene que sostenerla. En México lo hacen madres, hermanas, colectivos con aguja e hilo y bote de pintura. ¿Qué dice de nosotros que el archivo más honesto de nuestras ausencias no esté en una oficina de gobierno sino en un muro de Juárez y en un bordado de Torreón? ¿Y qué haríamos —qué haríamos de verdad— si el nombre bordado fuera el nuestro? La conversación queda abierta. Escríbenos: cuéntanos qué memoria estás sosteniendo tú.', 'On February 18, 2026, in Ciudad Juarez, five new faces appeared on a wall. They were not missing-person flyers or case-file numbers. They were Alfonso Guadian, Mauricio Maese, Jorge Ernesto Alanis, Juan Antonio Campos, and Raymundo Ivan Alvarez, painted not by how they vanished but by how they lived: their trade, their food, their favorite colors. The collective Familias Unidas por la Verdad y la Justicia unveiled the murals after an art-therapy process led by the artist Ana Infante, who summed it up without ornament: "This memorial is resistance. They are people who are loved and awaited." Since 2021, the Memorial Memoria Viva has worked as more than a wall. It is a meeting point, a place to organize, a way for those who search to hold one another up.

There is an uncomfortable idea at the heart of this art, and it is worth stating plainly. When the state turns a person into a figure in a statistic it would rather not update, naming that person becomes a political act. Painting a face is a refusal of the arithmetic of forgetting. That is why the most urgent public art of this cycle in Mexico does not hang in air-conditioned museums. It is painted on walls and embroidered in public squares, by the hands of those who carry the absence.

The thread, literally, appears in Torreon. On May 7, 2026, the collective Voz que clama justicia por personas desaparecidas embroidered the names and case files of their disappeared onto cloth in the Plaza Mayor, with one clear demand to the authorities: do not doctor the numbers. The gesture is precise and devastating. Embroidery takes the cold data of the case file, that bureaucratic language built to depersonalize, and returns it to the body, to the needle, to the slow time of someone stitching a name one point at a time in a public space. Where the official report summarizes, the thread insists. Where the statistic rounds off, the cloth names.

In Mexico City, during the Day of the Searching Mothers, the Colectivo Hilos intervened on a monument with a collective work of red cloth, folded into the national march of searching mothers advancing toward the Attorney General''s office. Red as a metaphor for femicide and disappearance turns the official stone, the kind of monument the state raises to its own version of history, into a canvas of mourning and accusation. For a day, the city becomes an archive of open wounds that no one was authorized to close.

Three cities, three materials, one question scaling upward: from the wall to the textile, from the neighborhood to the plaza. And the arc does not close at Mexico''s border. At the 61st Venice Biennale of 2026, titled "In Minor Keys," the Argentine pavilion presents "Visible Darkness: The Long Shadow of the Dictatorship," organized by the Museum of Modern Art of Buenos Aires, on state terrorism. The memory of the Southern Cone and the disappearances of present-day Mexico speak to each other without need of translation. In both cases, art does the work the institutions refused to do, holding memory when power prefers silence.

It is worth pausing on what these works are not. They are not triumphal monuments or aesthetic catharsis for the visitor. They are objects of use: points of organization, spaces of therapy, tools of demand. Art here does not illustrate the struggle; it is the struggle in its most stubborn form, the act of naming when naming is costly and painful. Ana Infante said it with an economy no critic could improve: people who are loved and awaited.

That leaves the question running through all of this, and we prefer to leave it open rather than resolved. When the state abandons memory, someone has to hold it. In Mexico that someone is mothers, sisters, collectives with a needle and thread and a can of paint. What does it say about us that the most honest archive of our absences is not in a government office but on a wall in Juarez and in an embroidery in Torreon? And what would we do, what would we truly do, if the stitched name were our own? The conversation stays open. Write to us: tell us what memory you are holding.',
     '/covers/arte-bordado.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;
