-- ═══════════════════════════════════════════════════════════════
-- Sin Tachar — PUBLICAR TODO (un solo Run). Idempotente (no duplica).
-- ⚠️ Córrelo DESPUÉS de que Vercel quede Ready (por las portadas SVG).
-- 8 artículos: IA, Injusticia, Música, Arte, Derechos humanos, 3× Videojuegos.
-- ═══════════════════════════════════════════════════════════════

-- ▼▼▼ publish-post-ia-segura ▼▼▼
-- Sin Tachar — publicar artículo de IA segura (pega TODO en Supabase → SQL Editor → Run).
-- Queda PUBLICADO en /es y /en, autorado por tu admin. Cambia el email si te registraste con otro.
do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then
    raise exception 'No encontré ese usuario. Regístrate primero o cambia el email en este script.';
  end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'ia-segura', 'cuando-el-agente-obedece-al-atacante',
     'Cuando el agente obedece al atacante: los riesgos reales de la IA agéntica en 2026', 'When the Agent Obeys the Attacker: The Real Risks of Agentic AI in 2026',
     'La IA que lee tu correo, navega y ejecuta código trajo consigo un problema que la industria ya no llama bug, sino condición estructural: la inyección de prompts. Repasamos los incidentes verificados de 2026 y quién termina cargando con el riesgo.', 'The AI that reads your email, browses the web, and runs code brought a problem the industry no longer calls a bug but a structural condition: prompt injection. We walk through 2026''s verified incidents and ask who ends up carrying the risk.',
     'La IA agéntica dejó de ser una promesa de laboratorio. Ya no hablamos de un modelo que responde preguntas, sino de sistemas que leen tu correo, navegan la web, ejecutan código y llaman APIs por su cuenta. Con esa autonomía llegó un problema que buena parte del sector ya no clasifica como bug, sino como condición estructural: la inyección de prompts. Y la diferencia con un chatbot es brutal. Cuando engañas a un chatbot, obtienes una mala respuesta. Cuando engañas a un agente, obtienes una transacción fraudulenta, una fuga de datos o un sistema comprometido.

Para ordenar el riesgo, el investigador Simon Willison popularizó un marco que hoy usa medio sector: la trifecta letal. El peligro se dispara cuando un agente combina tres cosas a la vez: acceso a datos privados, exposición a contenido no confiable (correos, páginas web, PDFs, tickets) y capacidad de comunicarse hacia afuera. Si le quitas una sola pata, el riesgo cae. Es, hasta ahora, la guía de mitigación más accionable que existe, y su fuerza está en lo poco glamurosa que es: no promete una solución mágica, solo pide cerrar puertas.

No es teoría. En 2025, la firma Aim Labs documentó EchoLeak (CVE-2025-32711, con severidad crítica 9.3), el primer exploit zero-click conocido contra un sistema de IA en producción: Microsoft 365 Copilot. Un solo correo con instrucciones ocultas bastaba para que Copilot filtrara archivos internos hacia un servidor del atacante, sin que la persona hiciera un solo clic. Microsoft lo parchó ese mismo año, pero el mensaje quedó claro: la superficie de ataque ya no es lo que el usuario hace, sino lo que el agente lee.

En noviembre de 2025, Anthropic reportó GTG-1002: la primera campaña de ciberespionaje orquestada por IA a escala documentada públicamente. Un actor estatal chino manipuló Claude Code para atacar cerca de 30 objetivos —empresas de tecnología, banca y gobierno—, con la IA ejecutando entre el 80 y el 90 por ciento de las operaciones tácticas de forma autónoma, fragmentando tareas maliciosas en pasos que, uno por uno, parecían inocentes. Meses después, en marzo de 2026, la Unit 42 de Palo Alto documentó doce casos reales de inyección indirecta en la vida real, incluido reviewerpress[.]com, el primer caso observado de evasión de moderación publicitaria por IA, además de intentos de borrado de bases de datos y transacciones no autorizadas.

Aquí conviene el ángulo incómodo: quién carga con el riesgo. En casi todos estos casos la víctima no es quien diseñó el agente ni quien lanzó el ataque, sino el usuario final o el empleado cuyos datos filtra un asistente que creía estar haciendo su trabajo. El daño se externaliza hacia abajo. Por eso la honestidad importa tanto como la técnica.

Y ser honestos también significa marcar lo que no se pudo verificar. Circulan cifras llamativas —una brecha de 195 millones de registros gubernamentales vía modelos de IA, un router que drenó una wallet de 500 mil dólares, aumentos del 340 por ciento en incidentes, 88 por ciento de organizaciones afectadas— que solo aparecen en blogs comerciales, sin fuente primaria. Las dejamos fuera a propósito. El hype no protege a nadie.

Lo que sí funciona es concreto y poco espectacular: separar el contenido no confiable de las instrucciones del sistema (spotlighting), imponer una jerarquía de instrucciones, dar a las herramientas del agente permisos de mínimo privilegio, y cortar al menos una pata de la trifecta —por ejemplo, negar la salida externa arbitraria. No por casualidad la inyección de prompts sigue siendo el número uno del OWASP LLM Top 10 de 2026.

Si trabajas con agentes, la pregunta no es si confías en el modelo, sino qué puede tocar cuando alguien lo engaña. Cuéntanos: ¿qué agentes ya tienen las tres patas de la trifecta en tu organización, y cuál podrías cortar esta semana?', 'Agentic AI is no longer a lab promise. We are no longer talking about a model that answers questions, but about systems that read your email, browse the web, run code, and call APIs on their own. That autonomy brought a problem that much of the industry no longer files under bug, but under structural condition: prompt injection. And the contrast with a chatbot is stark. Trick a chatbot and you get a bad answer. Trick an agent and you get a fraudulent transaction, a data leak, or a compromised system.

To make sense of the risk, researcher Simon Willison popularized a framework half the sector now uses: the lethal trifecta. Danger spikes when an agent combines three things at once: access to private data, exposure to untrusted content (emails, web pages, PDFs, tickets), and the ability to communicate outward. Remove a single leg and the risk drops. So far it is the most actionable mitigation guide we have, and its strength lies in how unglamorous it is: it promises no magic fix, only that you close doors.

This is not theory. In 2025, the firm Aim Labs documented EchoLeak (CVE-2025-32711, rated critical at 9.3), the first known zero-click exploit against a production AI system: Microsoft 365 Copilot. A single email with hidden instructions was enough for Copilot to leak internal files to an attacker''s server, with no click from the user at all. Microsoft patched it that same year, but the message was clear: the attack surface is no longer what the user does, but what the agent reads.

In November 2025, Anthropic reported GTG-1002: the first publicly documented AI-orchestrated cyber-espionage campaign at scale. A Chinese state actor manipulated Claude Code to attack around 30 targets —technology firms, banking, government— with the AI carrying out roughly 80 to 90 percent of the tactical operations autonomously, breaking malicious tasks into steps that, one by one, looked innocent. Months later, in March 2026, Palo Alto''s Unit 42 documented twelve real cases of indirect injection in the wild, including reviewerpress[.]com, the first observed case of AI ad-moderation evasion, alongside attempts to wipe databases and push unauthorized transactions.

Here is the uncomfortable angle: who carries the risk. In nearly all of these cases the victim is neither the agent''s designer nor the attacker, but the end user or the employee whose data gets leaked by an assistant that believed it was doing its job. The harm is externalized downward. That is why honesty matters as much as technique.

And being honest also means flagging what could not be verified. Eye-catching numbers circulate —a breach of 195 million government records via AI models, a router that drained a $500K wallet, a 340 percent rise in incidents, 88 percent of organizations affected— that appear only in commercial blogs, with no primary source. We are leaving them out on purpose. Hype protects no one.

What does work is concrete and unspectacular: separate untrusted content from system instructions (spotlighting), enforce an instruction hierarchy, give the agent''s tools least-privilege permissions, and cut at least one leg of the trifecta —for example, deny arbitrary external output. It is no accident that prompt injection remains number one on the 2026 OWASP LLM Top 10.

If you work with agents, the question is not whether you trust the model, but what it can touch when someone tricks it. Tell us: which of your agents already have all three legs of the trifecta wired up, and which one could you cut this week?',
     'https://picsum.photos/seed/agentic-injection-2026/1200/900', 'published', now())
  on conflict (slug) do nothing;
end $$;

-- ▼▼▼ publish-post-injusticia ▼▼▼
-- Sin Tachar — publicar artículo de Injusticia social (pega TODO en Supabase → SQL Editor → Run).
-- Queda PUBLICADO en /es y /en, autorado por tu admin. Cambia el email si usaste otro.
-- ⚠️ Córrelo DESPUÉS de que Vercel redespliegue (para que exista la portada SVG).
do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then
    raise exception 'No encontré ese usuario. Regístrate primero o cambia el email en este script.';
  end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'injusticia', 'cuando-el-sistema-dice-no',
     'Cuando el sistema dice "no": el costo humano de decidir por algoritmo', 'When the System Says "No": The Human Cost of Deciding by Algorithm',
     'Gobiernos que prometieron eficiencia están dejando sin ayuda a quienes menos margen tienen. El algoritmo no sufre el error; lo sufre una madre gitana, un anciano con discapacidad, una familia migrante. Y México acaba de poner un requisito biométrico en el camino de su pensión.', 'Governments that promised efficiency are cutting off aid to the people with the least room to absorb the loss. The algorithm doesn''t suffer the error; a Roma mother, a disabled elder, a migrant family does. And Mexico has just placed a biometric requirement on the path to its pension.',
     'Antes de que un funcionario la mirara a los ojos, un sistema informático ya había decidido que no merecía ayuda. En Serbia, la Tarjeta Social cruza alrededor de 130 tipos de datos para calcular quién tiene derecho a la asistencia del Estado. Desde 2022, más de 60,000 personas quedaron fuera de esa ayuda —23,000 solo en los primeros diez meses—, según el Grupo de Trabajo de la ONU sobre Empresas y Derechos Humanos. No es un accidente estadístico repartido al azar: el golpe cae de forma desproporcionada sobre la comunidad romaní (gitana) y sobre personas con discapacidad, cuyos ingresos informales el sistema malinterpreta como riqueza oculta. Amnistía Internacional lo describe sin eufemismos: el sistema refuerza una discriminación estructural que ya existía.

Conviene decir con claridad qué está en juego y qué no. No hablamos de robots que se rebelan ni de un debate abstracto sobre inteligencia artificial. Hablamos de decisiones cotidianas —conceder o negar una medicina, una pensión, un plato de comida— que los Estados han empezado a delegar en sistemas automáticos, y del daño concreto que eso produce cuando el sistema se equivoca. Porque el algoritmo no pasa hambre. Quien pasa hambre es la persona a la que el sistema, en silencio, marcó como indebida.

El patrón se repite en países muy distintos. En junio de 2026, Amnistía Internacional publicó "Automating Suspicion", un informe que documenta cómo los sistemas de perfilado de riesgo generan acusaciones falsas contra grupos ya marginados —personas racializadas, con discapacidad o enfermedad crónica, de bajos ingresos y migrantes— en Australia, Dinamarca, Francia y Países Bajos. El caso australiano, conocido como Robodebt, llegó a acusar de fraude a unas 400,000 personas por deudas que el propio algoritmo inventaba. Amnistía no pide ajustar la máquina: pide prohibir estos sistemas en contextos de alto riesgo, porque los considera incompatibles con el derecho internacional.

Tampoco es un problema lejano de Europa o de las antípodas. En Estados Unidos, el estado de Tennessee pagó a la consultora Deloitte más de 400 millones de dólares por TennCare Connect, el sistema que decide quién accede a Medicaid, el seguro médico para personas de bajos ingresos. Un juez federal falló que el sistema cargaba mal los datos, asignaba a las personas al hogar equivocado y negó ilegalmente cobertura de salud a miles, incluidas personas con discapacidad. Detrás de esa palabra —"miles"— hay gente que se quedó sin tratamiento mientras un software procesaba mal su expediente.

Aquí es donde América Latina debe mirarse con honestidad, sin caer en la alarma fácil. Desde febrero de 2026, la CURP biométrica es obligatoria en México para trámites y programas sociales, y el gobierno la exigirá para registrarse en la Pensión del Bienestar. Es importante ser justos: hasta la fecha no existe un caso documentado de una pensión negada o suspendida en México por un fallo del sistema. No lo afirmamos, porque no ha ocurrido o no se ha probado. Pero sí señalamos un punto de fricción conocido. Un requisito biométrico obligatorio para cobrar una pensión es exactamente el tipo de barrera que en Serbia dejó fuera a los más vulnerables: el adulto mayor rural sin documentos en regla, la persona cuya huella dactilar el lector no reconoce, quien no puede desplazarse a registrarse. Lo levantamos como advertencia, no como acusación. La lección de los otros países es que el momento de vigilar un sistema así es antes de que produzca su primera víctima, no después.

La historia reciente ya dejó un aviso. En Países Bajos, el escándalo del toeslagenaffaire acusó falsamente de fraude a unas 35,000 familias, muchas de origen migrante, y en 2021 tumbó al gobierno. Cuando Ámsterdam intentó construir después un sistema de bienestar "justo", en junio de 2025 tuvo que admitir que había fracasado.

La eficiencia no es un valor neutral cuando su precio lo paga siempre la misma gente. Detrás de cada expediente rechazado hay una persona que ese día no comió, no se trató o no cobró lo que le correspondía. Nombrar eso —exigir que un ser humano pueda revisar la decisión de una máquina, que exista un recurso real, que nadie pierda su pensión por un lector de huellas— no es estar en contra de la tecnología. Es estar a favor de las personas. ¿Qué salvaguardas deberíamos exigir antes de que un sistema automático decida quién merece ayuda en tu país? Esa conversación empieza ahora.', 'Before a caseworker ever looked her in the eye, a computer had already decided she didn''t deserve help. In Serbia, the Social Card system cross-references some 130 types of data to calculate who qualifies for state assistance. Since 2022, more than 60,000 people have been cut off from that aid—23,000 in the first ten months alone—according to the UN Working Group on Business and Human Rights. This is not a statistical accident spread evenly across the population: the blow falls disproportionately on the Roma community and on people with disabilities, whose informal earnings the system misreads as hidden wealth. Amnesty International describes it without euphemism: the system reinforces a structural discrimination that was already there.

It is worth being clear about what is at stake and what is not. We are not talking about robots that rebel, nor about an abstract debate over artificial intelligence. We are talking about everyday decisions—granting or denying a medicine, a pension, a plate of food—that states have begun to hand over to automated systems, and about the concrete harm that follows when the system gets it wrong. Because the algorithm does not go hungry. The one who goes hungry is the person the system quietly flagged as undeserving.

The pattern repeats across very different countries. In June 2026, Amnesty International published "Automating Suspicion," a report documenting how risk-profiling systems generate false accusations against already marginalized groups—racialized people, those with disabilities or chronic illness, low-income people, and migrants—in Australia, Denmark, France, and the Netherlands. Australia''s case, known as Robodebt, ended up accusing roughly 400,000 people of fraud over debts the algorithm itself invented. Amnesty is not asking for the machine to be fine-tuned: it is calling for these systems to be banned in high-risk contexts, because it deems them incompatible with international law.

Nor is this a distant problem confined to Europe or the far side of the world. In the United States, the state of Tennessee paid the consultancy Deloitte more than 400 million dollars for TennCare Connect, the system that decides who gets Medicaid, the health coverage for low-income people. A federal judge ruled that the system loaded data incorrectly, assigned people to the wrong household, and illegally denied health coverage to thousands, including people with disabilities. Behind that word—"thousands"—are people left without treatment while a piece of software mishandled their file.

This is where Latin America must look at itself honestly, without slipping into easy alarm. Since February 2026, the biometric CURP has been mandatory in Mexico for official procedures and social programs, and the government will require it to register for the Pensión del Bienestar, the old-age welfare pension. It is important to be fair: to date there is no documented case of a pension in Mexico being denied or suspended because of a system failure. We do not claim there is, because it has not happened—or has not been proven. But we do flag a known point of friction. A mandatory biometric requirement to collect a pension is exactly the kind of barrier that, in Serbia, shut out the most vulnerable: the rural elder without papers in order, the person whose fingerprint the reader cannot read, the one who cannot travel to register. We raise it as a warning, not an accusation. The lesson from other countries is that the time to watch a system like this is before it produces its first victim, not after.

Recent history has already left a warning. In the Netherlands, the toeslagenaffaire scandal falsely accused some 35,000 families, many of migrant background, of fraud, and in 2021 it brought down the government. When Amsterdam later tried to build a "fair" welfare system, by June 2025 it had to admit the attempt had failed.

Efficiency is not a neutral value when the same people always pay its price. Behind every rejected file is a person who that day did not eat, did not get treated, or did not receive what was owed to them. Naming that—demanding that a human being be able to review a machine''s decision, that a real avenue of appeal exist, that no one lose their pension to a fingerprint reader—is not being against technology. It is being for people. What safeguards should we demand before an automated system decides who deserves help in your country? That conversation starts now.',
     '/covers/injusticia-algoritmica.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;

-- ▼▼▼ publish-posts-musica-arte ▼▼▼
-- Sin Tachar — publicar artículos de MÚSICA y ARTE (pega TODO en Supabase → SQL Editor → Run).
-- Publicados en /es y /en, autorados por tu admin. ⚠️ Córrelo DESPUÉS del redeploy de Vercel (por las portadas SVG).
do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then
    raise exception 'No encontré ese usuario. Regístrate primero o cambia el email.';
  end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'musica', 'corridos-censura-mexico-cuando-callar-la-cancion',
     'Cuando callar la canción no calla la violencia: los corridos entre la censura y la crónica', 'When Silencing the Song Doesn''t Silence the Violence: Mexico''s Corridos Between Censorship and Chronicle',
     'En abril de 2025 un público destrozó los instrumentos sobre el escenario porque un cantante obedeció a la autoridad y se negó a tocar narcocorridos. Detrás de esa escena hay un año en que diez estados mexicanos prohibieron uno de los géneros más escuchados del país, Estados Unidos revocó visas y el gobierno respondió con un concurso para "orientar" las letras. La pregunta sigue abierta: ¿se puede callar una canción sin callar aquello que la produjo?', 'In April 2025 an audience smashed the instruments on stage because a singer obeyed the authorities and refused to play narcocorridos. Behind that scene lies a year in which ten Mexican states banned one of the country''s most-streamed genres, the United States revoked visas, and the government answered with a contest to "reorient" the lyrics. The question stays open: can you silence a song without silencing what produced it?',
     'El 11 de abril de 2025, en el palenque de la Feria de Texcoco, Luis R. Conríquez subió al ruedo y anunció lo que muchos no querían escuchar: por disposición oficial, esa noche no habría narcocorridos. Lo que siguió no fue un silencio respetuoso, sino una revuelta. El público lo abucheó, lanzó objetos y terminó destrozando los instrumentos sobre el escenario; el show acabó en desalojo, y una presentación posterior en Metepec fue cancelada. En esa escena —un cantante que acata a la autoridad y un público que se siente traicionado— está el nudo del año más tenso para uno de los géneros más escuchados de México.

Los corridos tumbados, esa fusión del regional mexicano con el trap y el hip-hop que llevó a artistas como Natanael Cano y Junior H a lo más alto del streaming global, arrastran una vieja contradicción: son, a la vez, crónica de un país en guerra narrada desde abajo y, en su vertiente más cruda, vitrina que romantiza a los capos. En 2025 esa tensión estalló en política pública.

Durante ese año, diez estados —entre ellos Michoacán, Jalisco, Nayarit, Chihuahua, Aguascalientes, Baja California, Guanajuato, Quintana Roo, Querétaro y el Estado de México— restringieron los narcocorridos en eventos públicos, con multas millonarias y procesos por "apología del delito". Chihuahua había sido pionero desde 2023, con sanciones que iban de 735 mil a 1.35 millones de pesos. Sinaloa y Sonora suspendieron conciertos alegando seguridad. El costo para los artistas fue inmediato: giras interrumpidas, autocensura sobre el escenario y el miedo a que una canción se volviera delito.

El caso más sonado cruzó la frontera. A fines de marzo de 2025, Los Alegres del Barranco proyectaron la imagen de "El Mencho", líder del CJNG, durante un concierto en un recinto de la Universidad de Guadalajara. Estados Unidos les revocó la visa, Jalisco abrió una carpeta de investigación y, más tarde, un juez les concedió un amparo en nombre de la libertad de expresión artística. Natanael Cano y Junior H también enfrentaron sanciones e indagatorias. La censura, lejos de apagar el género, lo empujó al centro del debate nacional.

La respuesta del gobierno federal no fue prohibir, sino orientar. En abril de 2025 la presidenta Claudia Sheinbaum lanzó "México Canta", un concurso binacional que reunió a unos 15 mil jóvenes de ambos lados de la frontera para componer canciones "sin apología de la violencia". En la final, con 222,955 votos, ganaron Sergio Maya, de Hidalgo, con "Quiero soñar", y Carmen María junto a Galia Siurob, de Tijuana. En mayo de 2026 Sheinbaum presentó la segunda edición desde Palacio Nacional, acompañada nada menos que por Junior H y Majo Aguilar: el mismo Estado que multa el género buscaba ahora reencauzarlo.

Aquí está lo que incomoda. Los corridos no inventaron la violencia que narran; la registran, a veces con complacencia, a veces como el único archivo que ciertas comunidades tienen de su propia herida. Prohibir la canción no desaparece los desplazamientos, las desapariciones ni el poder real de los cárteles que la canción, en su peor cara, celebra. Pero dejarla intacta tampoco es neutral cuando esas letras convierten a un capo en héroe. Entre la libertad de expresión y la responsabilidad sobre lo que se glorifica, México lleva dos años sin encontrar la nota justa, y en 2026 la discusión sigue abierta.

Nos interesa lo que ustedes escuchan en todo esto. ¿Es un corrido una crónica que incomoda al poder o una publicidad que le hace el trabajo al crimen? ¿Puede el Estado "reeducar" un género sin volverse censor? Cuéntennos desde dónde lo oyen: la conversación, como la música, apenas empieza.', 'On April 11, 2025, at the palenque of the Texcoco Fair, Luis R. Conríquez stepped into the ring and announced what many did not want to hear: by official order, there would be no narcocorridos that night. What followed was not a respectful silence but a riot. The crowd booed him, threw objects, and ended up smashing the instruments on stage; the show ended in evacuation, and a later performance in Metepec was canceled. In that scene —a singer obeying the authorities and an audience that feels betrayed— lies the knot of the tensest year for one of Mexico''s most-streamed genres.

Corridos tumbados, that fusion of regional Mexican music with trap and hip-hop that pushed artists like Natanael Cano and Junior H to the top of global streaming, carry an old contradiction: they are at once a chronicle of a country at war told from below and, in their rawest form, a showcase that romanticizes the kingpins. In 2025 that tension exploded into public policy.

Over that year, ten states —among them Michoacán, Jalisco, Nayarit, Chihuahua, Aguascalientes, Baja California, Guanajuato, Quintana Roo, Querétaro, and the State of Mexico— restricted narcocorridos at public events, with steep fines and prosecutions for "apología del delito," the glorification of crime. Chihuahua had been the pioneer since 2023, with penalties ranging from 735,000 to 1.35 million pesos. Sinaloa and Sonora suspended concerts citing security. The cost to artists was immediate: interrupted tours, self-censorship on stage, and the fear that a song might become a crime.

The most notorious case crossed the border. In late March 2025, Los Alegres del Barranco projected the image of "El Mencho," leader of the CJNG cartel, during a concert at a University of Guadalajara venue. The United States revoked their visas, Jalisco opened an investigation, and later a judge granted them an injunction in the name of artistic freedom of expression. Natanael Cano and Junior H also faced sanctions and inquiries. Censorship, far from muffling the genre, pushed it to the center of the national debate.

The federal government''s response was not to ban but to redirect. In April 2025, President Claudia Sheinbaum launched "México Canta," a binational contest that gathered some 15,000 young people from both sides of the border to compose songs "without glorifying violence." In the final, with 222,955 votes, the winners were Sergio Maya, from Hidalgo, with "Quiero soñar," and Carmen María alongside Galia Siurob, from Tijuana. In May 2026, Sheinbaum presented the second edition from the National Palace, accompanied by none other than Junior H and Majo Aguilar: the same state that fines the genre was now trying to steer it.

Here is what unsettles. Corridos did not invent the violence they narrate; they record it, sometimes with complacency, sometimes as the only archive certain communities have of their own wound. Banning the song does not erase the displacements, the disappearances, or the real power of the cartels that the song, at its worst, celebrates. But leaving it untouched is not neutral either, when those lyrics turn a kingpin into a hero. Between freedom of expression and responsibility for what gets glorified, Mexico has spent two years unable to find the right note, and in 2026 the discussion remains open.

We care about what you hear in all this. Is a corrido a chronicle that discomforts power, or advertising that does crime''s work for it? Can the state "reeducate" a genre without becoming a censor? Tell us where you are listening from: the conversation, like the music, is only just beginning.',
     '/covers/musica-corridos.svg', 'published', now()),
    (admin_id, 'arte', 'arte-memoria-buscadoras-mexico-2026',
     'Bordar un nombre para que no lo borre la cifra', 'Stitching a Name So the Statistics Can''t Erase It',
     'De un muro en Ciudad Juárez a un bordado en Torreón, las familias buscadoras de México convirtieron el arte en el último lugar donde sus desaparecidos siguen teniendo cara, oficio y color favorito. No es decoración: es resistencia contra el olvido de Estado.', 'From a wall in Ciudad Juarez to embroidery in Torreon, Mexico''s searching families have made art the last place where their disappeared still have a face, a trade, a favorite color. It isn''t decoration: it''s resistance against a state that would rather they be forgotten.',
     'El 18 de febrero de 2026, en Ciudad Juárez, cinco rostros nuevos aparecieron en un muro. No eran fichas de búsqueda ni cifras de expediente. Eran Alfonso Guadián, Mauricio Maese, Jorge Ernesto Alanís, Juan Antonio Campos y Raymundo Iván Álvarez, pintados no por cómo desaparecieron sino por cómo vivían: su oficio, su comida, sus colores favoritos. El colectivo Familias Unidas por la Verdad y la Justicia develó los murales tras un proceso de arteterapia coordinado por la artista Ana Infante, que lo resumió sin adornos: "Este memorial es resistencia. Son personas amadas y esperadas." El Memorial Memoria Viva funciona desde 2021 como algo más que una pared: es punto de encuentro, de organización, de sostén entre quienes buscan.

Hay una idea incómoda en el centro de este arte, y conviene decirla de frente. Cuando el Estado convierte a una persona en un número de una estadística que además prefiere no actualizar, nombrarla se vuelve un acto político. Pintar su cara es negarse a la aritmética del olvido. Por eso lo que ocurre en México este ciclo no cuelga en museos con aire acondicionado: se pinta en muros y se borda en plazas, con las manos de quienes cargan la ausencia.

El hilo, literalmente, aparece en Torreón. El 7 de mayo de 2026, el colectivo Voz que clama justicia por personas desaparecidas bordó en la Plaza Mayor los nombres y expedientes de sus desaparecidos, con una exigencia clara a las autoridades: no maquillar las cifras. El gesto es preciso y demoledor. El bordado toma el dato frío del expediente —ese lenguaje burocrático que despersonaliza— y lo devuelve al cuerpo, a la aguja, al tiempo lento de quien cose un nombre puntada por puntada en el espacio público. Donde el informe oficial resume, el hilo insiste. Donde la cifra redondea, la tela nombra.

En la Ciudad de México, en el marco del Día de las Madres Buscadoras, el Colectivo Hilos intervino un monumento con una pieza colectiva de tela roja, integrada a la marcha nacional de madres buscadoras que avanzaba rumbo a la Fiscalía General de la República. El rojo como metáfora de los feminicidios y las desapariciones convierte la piedra oficial —esos monumentos que el Estado erige a su propia versión de la historia— en un lienzo de duelo y denuncia. La ciudad se vuelve, por un día, un archivo de heridas abiertas que nadie autorizó a cerrar.

Tres ciudades, tres materiales, una misma pregunta escalando: del muro al textil, del barrio a la plaza. Y el arco no se cierra en México. En la 61ª Bienal de Venecia de 2026, titulada "In Minor Keys", el pabellón argentino presenta "Oscuridad visible: la larga sombra de la dictadura", organizado por el Museo de Arte Moderno de Buenos Aires, sobre el terrorismo de Estado. La memoria del Cono Sur y las desapariciones del México actual dialogan sin necesidad de traducción: en ambos casos, el arte hace el trabajo que las instituciones no quisieron hacer, sostener la memoria cuando el poder prefiere el silencio.

Vale la pena detenerse en lo que estas obras no son. No son monumentos triunfales ni catarsis estética para el visitante. Son objetos de uso: puntos de organización, espacios de terapia, herramientas de exigencia. El arte aquí no ilustra la lucha; es la lucha en su forma más tenaz, la de nombrar cuando nombrar cuesta y duele. Ana Infante lo dijo con una economía que ningún crítico mejoraría: personas amadas y esperadas.

Queda la pregunta que atraviesa todo esto y que preferimos dejar abierta, no resuelta. Cuando el Estado abandona la memoria, alguien tiene que sostenerla. En México lo hacen madres, hermanas, colectivos con aguja e hilo y bote de pintura. ¿Qué dice de nosotros que el archivo más honesto de nuestras ausencias no esté en una oficina de gobierno sino en un muro de Juárez y en un bordado de Torreón? ¿Y qué haríamos —qué haríamos de verdad— si el nombre bordado fuera el nuestro? La conversación queda abierta. Escríbenos: cuéntanos qué memoria estás sosteniendo tú.', 'On February 18, 2026, in Ciudad Juarez, five new faces appeared on a wall. They were not missing-person flyers or case-file numbers. They were Alfonso Guadian, Mauricio Maese, Jorge Ernesto Alanis, Juan Antonio Campos, and Raymundo Ivan Alvarez, painted not by how they vanished but by how they lived: their trade, their food, their favorite colors. The collective Familias Unidas por la Verdad y la Justicia unveiled the murals after an art-therapy process led by the artist Ana Infante, who summed it up without ornament: "This memorial is resistance. They are people who are loved and awaited." Since 2021, the Memorial Memoria Viva has worked as more than a wall. It is a meeting point, a place to organize, a way for those who search to hold one another up.

There is an uncomfortable idea at the heart of this art, and it is worth stating plainly. When the state turns a person into a figure in a statistic it would rather not update, naming that person becomes a political act. Painting a face is a refusal of the arithmetic of forgetting. That is why the most urgent public art of this cycle in Mexico does not hang in air-conditioned museums. It is painted on walls and embroidered in public squares, by the hands of those who carry the absence.

The thread, literally, appears in Torreon. On May 7, 2026, the collective Voz que clama justicia por personas desaparecidas embroidered the names and case files of their disappeared onto cloth in the Plaza Mayor, with one clear demand to the authorities: do not doctor the numbers. The gesture is precise and devastating. Embroidery takes the cold data of the case file, that bureaucratic language built to depersonalize, and returns it to the body, to the needle, to the slow time of someone stitching a name one point at a time in a public space. Where the official report summarizes, the thread insists. Where the statistic rounds off, the cloth names.

In Mexico City, during the Day of the Searching Mothers, the Colectivo Hilos intervened on a monument with a collective work of red cloth, folded into the national march of searching mothers advancing toward the Attorney General''s office. Red as a metaphor for femicide and disappearance turns the official stone, the kind of monument the state raises to its own version of history, into a canvas of mourning and accusation. For a day, the city becomes an archive of open wounds that no one was authorized to close.

Three cities, three materials, one question scaling upward: from the wall to the textile, from the neighborhood to the plaza. And the arc does not close at Mexico''s border. At the 61st Venice Biennale of 2026, titled "In Minor Keys," the Argentine pavilion presents "Visible Darkness: The Long Shadow of the Dictatorship," organized by the Museum of Modern Art of Buenos Aires, on state terrorism. The memory of the Southern Cone and the disappearances of present-day Mexico speak to each other without need of translation. In both cases, art does the work the institutions refused to do, holding memory when power prefers silence.

It is worth pausing on what these works are not. They are not triumphal monuments or aesthetic catharsis for the visitor. They are objects of use: points of organization, spaces of therapy, tools of demand. Art here does not illustrate the struggle; it is the struggle in its most stubborn form, the act of naming when naming is costly and painful. Ana Infante said it with an economy no critic could improve: people who are loved and awaited.

That leaves the question running through all of this, and we prefer to leave it open rather than resolved. When the state abandons memory, someone has to hold it. In Mexico that someone is mothers, sisters, collectives with a needle and thread and a can of paint. What does it say about us that the most honest archive of our absences is not in a government office but on a wall in Juarez and in an embroidery in Torreon? And what would we do, what would we truly do, if the stitched name were our own? The conversation stays open. Write to us: tell us what memory you are holding.',
     '/covers/arte-bordado.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;

-- ▼▼▼ publish-post-ddhh ▼▼▼
-- Sin Tachar — publicar artículo de Derechos humanos. ⚠️ Córrelo tras el redeploy de Vercel.
do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then raise exception 'No encontré ese usuario. Regístrate o cambia el email.'; end if;
  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'derechos-humanos', 'quienes-cuidan-la-tierra',
     'Quienes cuidan la tierra: los defensores que América Latina sigue enterrando', 'Those Who Guard the Land: The Defenders Latin America Keeps Burying',
     'En 2025, América Latina volvió a ser la región más letal para quienes defienden derechos humanos: al menos 358 personas asesinadas, la mayoría por defender la tierra. Las cifras, con nombre y fuente —y lo que todavía no sabemos.', 'In 2025, Latin America was again the deadliest region for human rights defenders: at least 358 people killed, most for defending the land. The figures, named and sourced —and what we still don''t know.',
     'En 2025, América Latina volvió a ser la región más letal del mundo para quienes defienden derechos humanos. No es una consigna: es lo que documentan, con nombres y cifras, las organizaciones que llevan más de una década contando cuerpos. Detrás de cada número hay una persona que decidió que un bosque, un río o su comunidad valían el riesgo.

Front Line Defenders registró al menos 358 personas defensoras asesinadas en 28 países durante 2025, según su Global Analysis 2025/26, publicado en junio de 2026. Los cinco países con más asesinatos fueron Colombia (165), México (43), Palestina (43), Brasil (22) y Honduras (13). Solo Colombia y México concentraron 208 casos: más de la mitad del total global registrado ese año.

El perfil de las víctimas dice tanto como las cifras. Quienes trabajaban por la tierra, el ambiente y los derechos campesinos fueron el grupo más atacado, con el 23.46% de los casos; les siguieron las personas defensoras de los derechos de los pueblos indígenas, con el 17.03%. No es casualidad: donde hay un territorio en disputa por minería, tala o agroindustria, suele haber alguien de la comunidad diciendo que no.

Global Witness, que mide específicamente a las personas defensoras de la tierra y el ambiente, contó 146 asesinadas o desaparecidas en el mundo durante 2024, y 117 de ellas —el 82%— en América Latina. Colombia encabezó por tercer año consecutivo, con 48 casos; Guatemala saltó de 4 a 20; México registró al menos 18 y Brasil al menos 12. El acumulado entre 2012 y 2024 llega a 2,253 personas. Los pueblos indígenas, que son cerca del 6% de la población mundial, fueron casi un tercio de las víctimas.

Matar no es la única forma de silenciar. Tanto Global Witness como CIVICUS advierten un cambio de táctica: la criminalización. El CIVICUS Monitor señala que las autoridades usan cada vez más el derecho penal para etiquetar a activistas como "criminales" o "terroristas", con cargos vagos, campañas de desprestigio y prisión preventiva prolongada. En Guatemala, la propia Comisión Interamericana de Derechos Humanos describió la criminalización como una práctica extendida, sostenida desde sectores del Ministerio Público y del poder judicial. Es una violencia más lenta, pero igual de eficaz para apagar una voz.

Hay un dato de contexto que rara vez se menciona. En 2025 la protección misma entró en crisis: Front Line Defenders documentó que 60 organizaciones perdieron en conjunto 45 millones de dólares anuales en apoyo directo a la protección, tras los recortes a la ayuda oficial al desarrollo. Menos escudos, los mismos blancos.

Conviene decir con claridad qué no sabemos. Estas cifras son mínimos verificados, no totales: dependen de lo que cada organización logró documentar y confirmar, y muchos casos quedan sin registrar, sobre todo en zonas de conflicto o bajo control de economías ilegales. Además, las metodologías difieren —Front Line Defenders cuenta a todo tipo de personas defensoras; Global Witness, solo a las de tierra y ambiente—, así que sus números no son directamente comparables ni se pueden sumar. Nombramos lo documentado sabiendo que la realidad probablemente es peor.

Detrás de cada una de estas cifras hay una persona que amaba un lugar y se atravesó para protegerlo. Nombrar el número es lo mínimo que podemos hacer; no olvidar es lo que sigue. ¿Conoces a alguien que defiende su territorio cerca de ti? Cuéntanoslo. Esta conversación se sostiene entre quienes se niegan a mirar para otro lado.', 'In 2025, Latin America was once again the deadliest region in the world for those who defend human rights. This is not a slogan: it is what the organizations that have spent more than a decade counting bodies document, with names and figures. Behind every number is a person who decided that a forest, a river, or their community was worth the risk.

Front Line Defenders recorded at least 358 human rights defenders killed across 28 countries in 2025, according to its Global Analysis 2025/26, published in June 2026. The five countries with the most killings were Colombia (165), Mexico (43), Palestine (43), Brazil (22), and Honduras (13). Colombia and Mexico alone accounted for 208 cases: more than half of the global total recorded that year.

The profile of the victims says as much as the figures. Those working for land, the environment, and peasant rights were the most attacked group, at 23.46% of cases; they were followed by defenders of Indigenous peoples'' rights, at 17.03%. It is no accident: wherever there is territory contested by mining, logging, or agribusiness, there tends to be someone from the community saying no.

Global Witness, which measures land and environmental defenders specifically, counted 146 killed or disappeared worldwide in 2024, and 117 of them —82%— in Latin America. Colombia led for the third consecutive year, with 48 cases; Guatemala jumped from 4 to 20; Mexico recorded at least 18 and Brazil at least 12. The cumulative toll between 2012 and 2024 reaches 2,253 people. Indigenous peoples, who make up about 6% of the world''s population, were nearly a third of the victims.

Killing is not the only way to silence someone. Both Global Witness and CIVICUS warn of a shift in tactics: criminalization. The CIVICUS Monitor notes that authorities increasingly use criminal law to label activists as "criminals" or "terrorists," through vague charges, smear campaigns, and prolonged pretrial detention. In Guatemala, the Inter-American Commission on Human Rights itself described criminalization as a widespread practice, sustained by sectors of the Attorney General''s Office and the judiciary. It is a slower violence, but just as effective at extinguishing a voice.

There is a piece of context that is rarely mentioned. In 2025, protection itself entered a crisis: Front Line Defenders documented that 60 organizations together lost 45 million dollars a year in direct protection support, following cuts to official development aid. Fewer shields, the same targets.

It is worth being clear about what we do not know. These figures are verified minimums, not totals: they depend on what each organization managed to document and confirm, and many cases go unrecorded, especially in zones of conflict or under the control of illegal economies. The methodologies also differ —Front Line Defenders counts all kinds of defenders; Global Witness, only those of land and environment— so their numbers are not directly comparable and cannot be added together. We name what is documented knowing that the reality is likely worse.

Behind each of these figures is a person who loved a place and stood in the way to protect it. Naming the number is the least we can do; not forgetting is what comes next. Do you know someone defending their land near you? Tell us. This conversation is held up by those who refuse to look away.',
     '/covers/ddhh-defensores.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;

-- ▼▼▼ publish-posts-videojuegos ▼▼▼
-- Sin Tachar — sección VIDEOJUEGOS + 2 artículos de Sony (pega TODO en SQL Editor → Run).
-- ⚠️ Córrelo DESPUÉS del redeploy de Vercel (por las portadas SVG).

-- Categoría Videojuegos (idempotente)
insert into public.categories (slug,name_es,name_en,sort_order)
  values ('videojuegos','Videojuegos','Video games',5) on conflict (slug) do nothing;
update public.categories set sort_order=6 where slug='ia-segura';

do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then raise exception 'No encontré ese usuario. Regístrate o cambia el email.'; end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'videojuegos', 'sony-fin-formato-fisico-playstation-quien-paga',
     'El disco que Sony deja morir: qué perdemos cuando el juego se vuelve licencia', 'The Disc Sony Is Letting Die: What We Lose When a Game Becomes a License',
     'Sony dejará de fabricar discos para juegos nuevos de PlayStation en enero de 2028. La letra chica ya la conocemos: comprar no es poseer. Y el costo lo paga quien depende del usado.', 'Sony will stop making discs for new PlayStation games in January 2028. We already know the fine print: buying isn''t owning. And the cost falls on whoever depends on the second-hand market.',
     'El 1 de julio de 2026 Sony lo hizo oficial en su propio blog: cesará la producción de discos físicos para todos los juegos nuevos que salgan en consolas PlayStation a partir de enero de 2028. Después de esa fecha, los títulos nuevos existirán únicamente en formato digital, en PlayStation Store o como códigos en tienda. Los juegos ya lanzados en disco, o que salgan antes de enero de 2028, no se ven afectados: seguirán funcionando, revendiéndose y existiendo. Sid Shuman, directivo de SIE, lo enmarcó como un movimiento de la industria que "se aleja de los discos físicos hacia lo digital". El comunicado no trae porcentajes ni cifras.

Aquí conviene ser honesto con los números, porque circulan dos que miden cosas distintas. Por un lado, medios reportan un ~85% digital contra 15% físico, pero eso es participación de ventas de software de juego completo en PS4/PS5, no un dato del blog oficial. Por otro, Slate cita que en 2024 los discos fueron apenas el 3% de todas las ventas de la marca PlayStation (que incluye hardware y servicios) y que la compañía movió alrededor de 70 millones de discos en 2025. Son cosas diferentes: no las mezclen. Sony, oficialmente, solo habla de "preferencia del consumidor".

El corazón del problema no es la nostalgia por el plástico. Es esto: comprar no es poseer. Los términos de PlayStation Network dicen, con todas sus letras, que "purchase" o "buy" no transfieren propiedad; todo se licencia de forma revocable. Y no es teoría. En junio de 2026 Sony avisó a usuarios de Reino Unido y Europa que el 1 de septiembre eliminaría 551 películas y series de StudioCanal ya "compradas", sin reembolso, porque venció el acuerdo de licencia. Ya había pasado antes con contenido de Discovery en 2023, revertido solo tras las protestas. Cuando el disco desaparece, esa cláusula deja de ser letra chica y se vuelve la única realidad.

De ahí sale el otro costo silencioso: la preservación. Las licencias caducan y los juegos se evaporan. Metal Gear Solid salió de tiendas digitales por líos con material de archivo; en un mundo sin disco, un juego así simplemente deja de existir. Cuando se planteó cerrar las tiendas de PS3 y Vita, se calculó que unos 2,200 juegos digitales dejarían de venderse, y 138 de ellos no existen en ninguna otra plataforma. La campaña Stop Killing Games recoge firmas, pero hasta ahora no ha conseguido ninguna reforma legal en Reino Unido, la UE ni Estados Unidos. El único contrapeso concreto es tímido: la ley californiana AB 2426, vigente desde enero de 2025, obliga a avisar cuando una "compra" digital es en realidad una licencia. Avisa; no impide que te la quiten.

¿Y quién paga la cuenta? El coleccionista pierde el objeto. El jugador de reventa pierde la forma de recuperar valor o de comprar barato de segunda mano. Y aquí va lo que el dossier no confirma con fuente específica para la región, así que lo digo como lectura y no como dato duro: en México y LatAm, donde el mercado usado abarata el acceso y donde el internet no siempre alcanza para descargar juegos cada vez más pesados, "sin disco" puede terminar significando "sin entrada". Un modelo 100% digital traslada ese costo al consumidor con menos margen, no al que ya paga suscripciones cómodo.

No es un adiós al plástico por capricho tecnológico. Es un cambio en la relación entre quien juega y quien vende: de dueño a arrendatario. La pregunta que dejamos abierta es tuya: ¿comprarías una biblioteca que la tienda puede apagar? ¿Te cambia la ecuación si vives donde el usado es la puerta de entrada? Cuéntanos en los comentarios cómo lo ves desde donde estás.', 'On July 1, 2026, Sony made it official on its own blog: it will stop producing physical discs for all new games launching on PlayStation consoles starting January 2028. After that date, new titles will exist in digital form only, on the PlayStation Store or as in-store codes. Games already released on disc, or launching before January 2028, are not affected: they will keep working, keep being resold, keep existing. Sid Shuman, an SIE director, framed it as an industry moving "away from physical discs and toward digital." The announcement carries no percentages and no figures.

It is worth being honest about the numbers, because two are circulating and they measure different things. On one hand, outlets report roughly 85% digital versus 15% physical, but that is the share of full-game software sales on PS4/PS5, not a figure from the official blog. On the other, Slate cites that in 2024 discs were just 3% of all PlayStation-brand sales (which includes hardware and services), and that the company moved around 70 million discs in 2025. These are not the same metric, so don''t blend them. Officially, Sony only talks about "consumer preference."

The heart of the issue is not nostalgia for plastic. It''s this: buying is not owning. PlayStation Network''s terms say, in plain words, that "purchase" or "buy" do not transfer ownership; everything is licensed on a revocable basis. And this is not theory. In June 2026, Sony told users in the UK and Europe that on September 1 it would remove 551 StudioCanal films and series they had already "purchased," with no refund, because the licensing deal expired. It had happened before with Discovery content in 2023, reversed only after backlash. When the disc disappears, that clause stops being fine print and becomes the only reality.

From there comes the other quiet cost: preservation. Licenses expire and games evaporate. Metal Gear Solid was pulled from digital stores over issues with archival footage; in a discless world, a game like that simply ceases to exist. When closing the PS3 and Vita stores was floated, it was estimated that some 2,200 digital games would stop being sold, and 138 of them exist on no other platform. The Stop Killing Games campaign is gathering signatures, but so far it has secured no legal reform in the UK, the EU, or the United States. The one concrete counterweight is timid: California''s AB 2426 law, in force since January 2025, requires sellers to disclose when a digital "purchase" is really a license. It warns you; it does not stop them from taking it away.

So who pays the bill? The collector loses the object. The resale player loses the way to recover value or buy cheap second-hand. And here is what the dossier does not confirm with a region-specific source, so I offer it as a reading rather than hard data: in Mexico and Latin America, where the used market makes access cheaper and where internet isn''t always enough to download increasingly large games, "no disc" can end up meaning "no entry." A 100% digital model shifts that cost onto the consumer with the least margin, not onto the one already paying subscriptions comfortably.

This is not a goodbye to plastic on a technological whim. It''s a shift in the relationship between the player and the seller: from owner to renter. The question we leave open is yours: would you buy a library the store can switch off? Does the math change if you live where used copies are the way in? Tell us in the comments how it looks from where you are.',
     '/covers/sony-formato-fisico.svg', 'published', now()),
    (admin_id, 'videojuegos', 'sony-pesos-mexico-dolar-20-50-playstation',
     'Sony cobrará en pesos en México: el "dólar a 20.50" que ya molesta a los jugadores', 'Sony will charge in pesos in Mexico: the "20.50 dollar" already upsetting players',
     'La PlayStation Store dejará de cobrar en dólares en México a partir del 20 de agosto de 2026. La letra chica: Sony fijará su propio tipo de cambio en 20.50 pesos por dólar, muy por encima del dólar real de ~17.4.', 'The PlayStation Store will stop charging in dollars in Mexico starting August 20, 2026. The fine print: Sony sets its own exchange rate at 20.50 pesos per dollar, well above the real ~17.4 dollar.',
     'Después de años vendiendo en dólares, la PlayStation Store empezará a mostrar y cobrar precios en pesos mexicanos. El anuncio se hizo público el 17 de julio de 2026 y el cambio se ejecutará durante una ventana de mantenimiento de la tienda entre el 18 y el 20 de agosto de 2026. La medida aplica también a Honduras y Nicaragua. Suena a buena noticia —adiós a la conversión mental y a las comisiones del banco— pero el costo real para quien paga está escondido en un número: Sony fijará su propio tipo de cambio interno en 20.50 pesos por dólar.

Ahí está el problema. Según los reportes de prensa, el tipo de cambio de mercado en esos mismos días de julio de 2026 rondaba los 17.38 a 17.52 pesos por dólar (el FIX de Banxico fue de 17.50 el 13 de julio, y el peso cerró en 17.38 el 15 de julio). Sony está aplicando un tipo de cambio más de 3 pesos por encima del real, un sobreprecio implícito cercano al 17 o 18 por ciento sobre la paridad de mercado, incluso antes de discutir impuestos.

El ejemplo que circuló en la prensa usa GTA 6 (79.99 dólares). Con el esquema actual, 79.99 dólares más unos 12.80 de impuesto dan alrededor de 92.79 dólares, es decir unos 1,626 pesos al cambio de mercado. Con el nuevo precio en pesos a 20.50, el cálculo periodístico da aproximadamente 1,640 pesos. La diferencia en ese ejemplo puntual es pequeña, y por eso medios como Xataka especulan que el 20.50 ya podría incluir el IVA del 16 por ciento. Hay que ser claros: eso NO está confirmado. Sony no aclaró si los impuestos seguirán cobrándose por separado, y ese es justo el dato que hoy no se puede afirmar. El ejemplo de GTA 6 es un cálculo de prensa, no una lista de precios oficial de Sony.

Conviene también matizar el propio "dólar a 20" del que todos hablan: lo confirmado es que Sony usará 20.50, no un redondo 20. Y el dólar real en julio de 2026 está en torno a 17.4, no en 20. Es decir, el número que Sony eligió para su tienda vive en un universo distinto al del mercado cambiario.

Vale la pena recordar por qué ocurre esto ahora, porque no fue voluntad de Sony. La Profeco actuó tras una queja de usuarios y notificó a la empresa que la ley mexicana obliga a exhibir precios en moneda nacional, advirtiendo posibles sanciones. El origen viene de una denuncia de agosto de 2025, cuando jugadores señalaron que el precio final con IVA solo aparecía en el último paso de la compra. El comunicado oficial de Sony lo vende como una simplificación, y en sus palabras están "simplificando las compras en PlayStation Store en México al mostrar los precios en Pesos Mexicanos". La comunidad no lo leyó igual: pasar a pesos era exactamente lo que se pedía, pero ante la falta de una explicación clara sobre el 20.50 y sobre el IVA, muchos jugadores mexicanos expresaron molestia en redes, temiendo terminar pagando más caro que con la conversión directa actual.

Este episodio no llega en el vacío. En abril de 2025 Sony ya había subido PS Plus en México y toda LatAm en todos sus niveles, con el plan anual Essential pasando de 54.99 a 64.99 dólares. La tienda de PlayStation, a diferencia de Xbox o Steam, ha operado históricamente en dólares en México, dejando el precio de cada juego a merced del tipo de cambio. Y el contexto de poder adquisitivo duele: el salario mínimo general subió a 315.04 pesos diarios desde enero de 2026. Un solo juego AAA de alrededor de 1,600 pesos supera cinco días de ese salario mínimo íntegro.

La pregunta abierta, y la que más importa a quien paga, es simple: ¿el 20.50 incluye o no el IVA? De esa respuesta depende que la migración a pesos sea un alivio o un aumento disfrazado. Hoy Sony no lo ha aclarado. ¿Tú qué crees que va a pasar cuando la tienda cambie el 20 de agosto? Cuéntanos en los comentarios cómo te está pegando el precio del gaming en México.', 'After years of selling in dollars, the PlayStation Store will start displaying and charging prices in Mexican pesos. The announcement became public on July 17, 2026, and the switch will happen during a store maintenance window between August 18 and August 20, 2026. The measure also applies to Honduras and Nicaragua. It sounds like good news, goodbye to mental math and bank conversion fees, but the real cost for whoever pays is hidden in one number: Sony will set its own internal exchange rate at 20.50 pesos per dollar.

That is the problem. According to press reports, the market exchange rate during those same days of July 2026 hovered between 17.38 and 17.52 pesos per dollar (Banxico''s FIX rate was 17.50 on July 13, and the peso closed at 17.38 on July 15). Sony is applying an exchange rate more than 3 pesos above the real one, an implicit markup close to 17 or 18 percent over the market rate, even before we get into taxes.

The example that circulated in the press uses GTA 6 (79.99 dollars). Under the current scheme, 79.99 dollars plus roughly 12.80 in tax comes to about 92.79 dollars, or around 1,626 pesos at the market rate. With the new peso price at 20.50, the journalistic calculation lands at approximately 1,640 pesos. The difference in that specific example is small, which is why outlets like Xataka speculate that the 20.50 might already include the 16 percent VAT. Let us be clear: that is NOT confirmed. Sony did not clarify whether taxes will still be charged separately, and that is exactly the data point no one can assert today. The GTA 6 example is a press calculation, not an official Sony price list.

It is also worth qualifying the "20 dollar" figure everyone is talking about: what is confirmed is that Sony will use 20.50, not a round 20. And the real dollar in July 2026 is around 17.4, not 20. In other words, the number Sony chose for its store lives in a different universe than the currency market.

It is worth remembering why this is happening now, because it was not Sony''s initiative. Profeco, Mexico''s consumer protection agency, acted after user complaints and notified the company that Mexican law requires displaying prices in national currency, warning of possible penalties. The origin traces back to a complaint in August 2025, when players pointed out that the final price with VAT only appeared at the last step of the purchase. Sony''s official statement frames it as a simplification, saying in its own words that it is "simplifying purchases on the PlayStation Store in Mexico by showing prices in Mexican Pesos." The community did not read it the same way: switching to pesos was exactly what was requested, but with no clear explanation about the 20.50 or the VAT, many Mexican players voiced frustration on social media, fearing they will end up paying more than under the current direct conversion.

This episode does not arrive in a vacuum. In April 2025 Sony had already raised PS Plus in Mexico and across Latin America at every tier, with the annual Essential plan going from 54.99 to 64.99 dollars. Unlike Xbox or Steam, the PlayStation store has historically operated in dollars in Mexico, leaving every game''s price at the mercy of the exchange rate. And the purchasing-power context stings: Mexico''s general minimum wage rose to 315.04 pesos per day as of January 2026. A single AAA game at around 1,600 pesos exceeds five full days of that minimum wage.

The open question, and the one that matters most to whoever pays, is simple: does the 20.50 include VAT or not? Whether the move to pesos is a relief or a disguised increase depends on that answer. Sony has not clarified it yet. What do you think will happen when the store changes on August 20? Tell us in the comments how gaming prices are hitting you in Mexico.',
     '/covers/sony-precios-mexico.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;

-- ▼▼▼ publish-post-videojuegos-industria ▼▼▼
-- Sin Tachar — (BONUS) artículo inaugural de Videojuegos: crisis laboral de la industria.
-- Opcional. Córrelo DESPUÉS del redeploy de Vercel.

-- Categoría Videojuegos (idempotente)
insert into public.categories (slug,name_es,name_en,sort_order)
  values ('videojuegos','Videojuegos','Video games',5) on conflict (slug) do nothing;
update public.categories set sort_order=6 where slug='ia-segura';

do $$
declare admin_id uuid;
begin
  select id into admin_id from auth.users where email = 'ricardo.martinez@inbest.cloud';
  if admin_id is null then raise exception 'No encontré ese usuario. Regístrate o cambia el email.'; end if;

  insert into public.posts
    (author_id, category_slug, slug, title_es, title_en, excerpt_es, excerpt_en, body_es, body_en, cover_image_url, status, published_at)
  values
    (admin_id, 'videojuegos', 'record-y-despido-costo-humano-del-videojuego',
     'El récord y el despido: quién paga la edad de oro del videojuego', 'The Record and the Layoff: Who Pays for Gaming''s Golden Age',
     'La industria del videojuego facturó una cifra histórica mientras despedía a decenas de miles de personas. Detrás del récord hay una crisis laboral que trabajadores, sindicatos y actores de voz empezaron a disputar.', 'The video game industry booked record revenue while laying off tens of thousands of people. Behind the record lies a labor crisis that workers, unions, and voice actors have begun to fight back against.',
     'En 2025 la industria del videojuego facturó una cifra que sus fundadores difícilmente habrían imaginado: alrededor de 201.600 millones de dólares. El mismo año, cerca de nueve mil personas que hacían esos juegos se quedaron sin trabajo. Esa es la fractura que define al medio en 2026: nunca se ganó tanto dinero, y nunca se despidió a tanta gente que lo generaba. El récord y el despido conviven en la misma hoja de cálculo, y entre ambos hay nombres, hipotecas y años de oficio.

El dato duele más al mirarlo de cerca. 2024 fue el peor año registrado por el sector: entre 14.800 y 15.600 puestos eliminados, según las estimaciones que compilan medios y analistas —no existe un censo oficial, así que conviene leerlas como cálculos agregados—, con un primer trimestre que concentró 8.619 despidos, el trimestre más alto de la historia de la industria. 2025 trajo unos 9.175, una cifra menor pero todavía por encima de la crisis de 2022. Y en julio de 2026, Microsoft anunció alrededor de 9.000 despidos globales, de los cuales unos 3.200 cayeron sobre su división de videojuegos, tocando estudios como Obsidian, id Software y ZeniMax Online.

No son solo números: son estudios enteros que dejaron de existir. Arkane Austin, Ready at Dawn, Volition y Riot Forge cerraron en 2024; Cliffhanger Games, de EA, en mayo de 2025; y Ubisoft Leamington. Cada cierre borra una cultura de trabajo, una manera de contar historias, una comunidad. Y el momento suele ser cruel: según los reportes, los recortes de Microsoft de julio de 2026 llegaron apenas un día antes del lanzamiento del DLC de DOOM: The Dark Ages, contenido que los mismos trabajadores despedidos habían terminado a marchas forzadas. El crunch, esa jornada extenuante que la industria normalizó durante décadas, no fue recompensado con estabilidad, sino con la carta de despido.

Frente a ese patrón, algo cambió: los trabajadores dejaron de aceptarlo en silencio. En julio de 2024, Bethesda Game Studios —241 personas entre artistas, diseñadores y programadores— se convirtió en el primer sindicato "wall-to-wall" de Microsoft, reconocido a través de la Communications Workers of America. Desde 2022, más de 3.500 trabajadores de Xbox se han sindicalizado. Y cuando los recortes de julio de 2026 alcanzaron a 440 puestos sindicalizados, la respuesta fue inédita: el 15 de julio de 2026 hubo marchas simultáneas en seis estudios de Xbox, la primera acción laboral multiestudio coordinada del sector, acompañada de cargos por prácticas laborales injustas en Estados Unidos y Canadá.

La otra gran batalla se libró en el terreno que más nos importa aquí: la inteligencia artificial. Los actores de voz y de captura de movimiento agrupados en SAG-AFTRA iniciaron huelga el 26 de julio de 2024, la suspendieron el 11 de junio de 2025 y ratificaron el acuerdo con un 95,04% a favor. Lograron aumentos compuestos y, sobre todo, protecciones concretas frente a la IA: consentimiento y divulgación obligatorios para crear réplicas digitales de su voz o su imagen, con derecho a suspender ese consentimiento durante una huelga. Es una de las primeras veces que una industria escribe, en un contrato, que la persona debe autorizar que una máquina la imite. No es una victoria menor: es una definición de dónde termina la eficiencia y empieza la dignidad.

Aquí no celebramos la épica del videojuego sin mirar quién la sostiene. Detrás de cada mundo abierto, cada doblaje que nos eriza la piel, cada final que recordamos años después, hay gente cuyo trabajo se volvió invisible justo cuando el negocio nunca estuvo mejor. La pregunta que deja 2026 no es cuánto factura la industria, sino a qué costo humano lo hace, y qué le debemos a quienes construyen los mundos donde jugamos.

¿Cómo lo ves tú? ¿Puede un medio seguir llamándose arte si trata así a sus artistas? Cuéntanos en los comentarios: queremos leerte.', 'In 2025 the video game industry booked a figure its founders could scarcely have imagined: roughly 201.6 billion dollars. That same year, close to nine thousand of the people who make those games lost their jobs. This is the fracture that defines the medium in 2026: never has so much money been made, and never have so many of the people generating it been let go. The record and the layoff share the same spreadsheet, and between the two there are names, mortgages, and years of craft.

The numbers hurt more up close. 2024 was the worst year on record for the sector: between 14,800 and 15,600 positions eliminated, according to estimates compiled by media outlets and analysts — there is no official census, so they are best read as aggregate calculations — with a first quarter that alone accounted for 8,619 layoffs, the highest single quarter in the industry''s history. 2025 brought around 9,175, a smaller figure but still above the 2022 crisis. And in July 2026, Microsoft announced roughly 9,000 global layoffs, some 3,200 of them falling on its gaming division, hitting studios such as Obsidian, id Software, and ZeniMax Online.

These are not just numbers: they are entire studios that ceased to exist. Arkane Austin, Ready at Dawn, Volition, and Riot Forge closed in 2024; EA''s Cliffhanger Games in May 2025; and Ubisoft Leamington. Each closure erases a working culture, a way of telling stories, a community. And the timing tends to be cruel: according to reports, Microsoft''s July 2026 cuts arrived barely a day before the launch of the DOOM: The Dark Ages DLC — content that the very workers being laid off had finished under grueling pressure. Crunch, the punishing overwork the industry normalized for decades, was rewarded not with stability but with a pink slip.

Against that pattern, something shifted: workers stopped accepting it in silence. In July 2024, Bethesda Game Studios — 241 people spanning artists, designers, and programmers — became Microsoft''s first "wall-to-wall" union, recognized through the Communications Workers of America. Since 2022, more than 3,500 Xbox workers have unionized. And when the July 2026 cuts reached 440 union positions, the response was unprecedented: on July 15, 2026, there were simultaneous marches at six Xbox studios, the first coordinated multi-studio labor action in the sector''s history, backed by unfair labor practice charges in the United States and Canada.

The other great battle was fought on the terrain we care about most here: artificial intelligence. The voice and motion-capture performers of SAG-AFTRA began their strike on July 26, 2024, suspended it on June 11, 2025, and ratified the agreement with 95.04% in favor. They won compound raises and, above all, concrete protections against AI: mandatory consent and disclosure to create digital replicas of their voice or likeness, with the right to withdraw that consent during a strike. It is one of the first times an industry has written into a contract that a person must authorize a machine to imitate them. This is no minor victory: it is a definition of where efficiency ends and dignity begins.

We do not celebrate the epic scale of video games without asking who holds it up. Behind every open world, every performance that raises the hairs on your arm, every ending we remember years later, there are people whose work became invisible precisely when the business had never been better. The question 2026 leaves us is not how much the industry earns, but at what human cost — and what we owe to those who build the worlds we play in.

How do you see it? Can a medium still call itself art if it treats its artists this way? Tell us in the comments: we want to hear from you.',
     '/covers/videojuegos-despidos.svg', 'published', now())
  on conflict (slug) do nothing;
end $$;

-- ▼ arreglo de portada de IA (usó picsum) ▼
update public.posts set cover_image_url='/covers/ia-agentica.svg' where slug='cuando-el-agente-obedece-al-atacante';
